//------------------------------------------------------------------------------
// <auto-generated>
//     File này được tạo tự động từ PLCConfig.json
//     Thời gian: 2025-10-29 (Initial version)
//     KHÔNG CHỈNH SỬA TRỰC TIẾP FILE NÀY!
//
//     Để regenerate file này, chạy:
//     PLCConfigManager manager = new PLCConfigManager();
//     manager.LoadConfig("PLCConfig.json");
//     manager.GenerateAddressesFile("PLCAddresses.Generated.cs");
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom;

namespace PLCKeygen
{
    /// <summary>
    /// Địa chỉ PLC được generate tự động từ PLCConfig.json
    /// PLC: Keyence_PLC_Main (192.168.1.100:8501)
    /// </summary>
    public static class PLCAddresses
    {
        public const string PLCName = "Keyence_PLC_Main";
        public const string IPAddress = "192.168.1.100";
        public const int Port = 8501;

        /// <summary>
        /// Địa chỉ Input (đầu vào)
        /// </summary>
        public static class Input
        {
            #region Port 1 Jog
            public const string P1_Step_Jog_Mode =  "MR02002";
            public const string P1_XJog_Plus =  "MR43701";
            public const string P1_XJog_Minus = "MR43702";
            public const string P1_XHome =      "MR43700";
            public const string P1_XReset =     "MR43705";
            public const string P1_XGo_ABS =    "MR43703";
            public const string P1_XGo_INC =    "MR43704";
            public const string P1_YJog_Plus =  "MR44001";
            public const string P1_YJog_Minus = "MR44002";
            public const string P1_YHome =      "MR44000";
            public const string P1_YReset =     "MR44005";
            public const string P1_YGo_ABS =    "MR44003";
            public const string P1_YGo_INC =    "MR44004";
            public const string P1_ZJog_Plus =  "MR44301";
            public const string P1_ZJog_Minus = "MR44302";
            public const string P1_ZHome =      "MR44300";
            public const string P1_ZReset =     "MR44305";
            public const string P1_ZGo_ABS =    "MR44303";
            public const string P1_ZGo_INC =    "MR44304";
            public const string P1_RIJog_Plus = "MR44601";
            public const string P1_RIJog_Minus ="MR44602";
            public const string P1_RIHome =     "MR44600";
            public const string P1_RIReset =    "MR44605";
            public const string P1_RIGo_ABS =   "MR44603";
            public const string P1_RIGo_INC =   "MR44604";
            public const string P1_ROJog_Plus = "MR44901";
            public const string P1_ROJog_Minus ="MR44902";
            public const string P1_ROHome =     "MR44900";
            public const string P1_ROReset =    "MR44905";
            public const string P1_ROGo_ABS =   "MR44903";
            public const string P1_ROGo_INC =   "MR44904";
            public const string P1_FJog_Plus =  "MR45201";
            public const string P1_FJog_Minus = "MR45202";
            public const string P1_FHome =      "MR45200";
            public const string P1_FReset =     "MR45205";
            public const string P1_FGo_ABS =    "MR45203";
            public const string P1_FGo_INC =    "MR45204";
            #endregion

            #region Port 2 Jog
            public const string P2_Step_Jog_Mode = "MR00002";
            public const string P2_XJog_Plus =  "MR40101";
            public const string P2_XJog_Minus = "MR40102";
            public const string P2_XHome =      "MR40100";
            public const string P2_XReset =     "MR40105";
            public const string P2_XGo_ABS =    "MR40103";
            public const string P2_XGo_INC =    "MR40104";
            public const string P2_YJog_Plus =  "MR40401";
            public const string P2_YJog_Minus = "MR40402";
            public const string P2_YHome =      "MR40400";
            public const string P2_YReset =     "MR40405";
            public const string P2_YGo_ABS =    "MR40403";
            public const string P2_YGo_INC =    "MR40404";
            public const string P2_ZJog_Plus =  "MR40701";
            public const string P2_ZJog_Minus = "MR40702";
            public const string P2_ZHome =      "MR40700";
            public const string P2_ZReset =     "MR40705";
            public const string P2_ZGo_ABS =    "MR40703";
            public const string P2_ZGo_INC =    "MR40704";
            public const string P2_RIJog_Plus = "MR41001";
            public const string P2_RIJog_Minus ="MR41002";
            public const string P2_RIHome =     "MR41000";
            public const string P2_RIReset =    "MR41005";
            public const string P2_RIGo_ABS =   "MR41003";
            public const string P2_RIGo_INC =   "MR41004";
            public const string P2_ROJog_Plus = "MR41301";
            public const string P2_ROJog_Minus ="MR41302";
            public const string P2_ROHome =     "MR41300";
            public const string P2_ROReset =    "MR41305";
            public const string P2_ROGo_ABS =   "MR41303";
            public const string P2_ROGo_INC =   "MR41304";
            public const string P2_FJog_Plus =  "MR41601";
            public const string P2_FJog_Minus = "MR41602";
            public const string P2_FHome =      "MR41600";
            public const string P2_FReset =     "MR41605";
            public const string P2_FGo_ABS =    "MR41603";
            public const string P2_FGo_INC =    "MR41604";
            #endregion

            #region Port 3 Jog
            public const string P3_Step_Jog_Mode = "MR03002";
            public const string P3_XJog_Plus =  "MR45501";
            public const string P3_XJog_Minus = "MR45502";
            public const string P3_XHome =      "MR45500";
            public const string P3_XReset =     "MR45505";
            public const string P3_XGo_ABS =    "MR45503";
            public const string P3_XGo_INC =    "MR45504";
            public const string P3_YJog_Plus =  "MR45801";
            public const string P3_YJog_Minus = "MR45802";
            public const string P3_YHome =      "MR45800";
            public const string P3_YReset =     "MR45805";
            public const string P3_YGo_ABS =    "MR45803";
            public const string P3_YGo_INC =    "MR45804";
            public const string P3_ZJog_Plus =  "MR46101";
            public const string P3_ZJog_Minus = "MR46102";
            public const string P3_ZHome =      "MR46100";
            public const string P3_ZReset =     "MR46105";
            public const string P3_ZGo_ABS =    "MR46103";
            public const string P3_ZGo_INC =    "MR46104";
            public const string P3_RIJog_Plus = "MR46401";
            public const string P3_RIJog_Minus ="MR46402";
            public const string P3_RIHome =     "MR46400";
            public const string P3_RIReset =    "MR46405";
            public const string P3_RIGo_ABS =   "MR46403";
            public const string P3_RIGo_INC =   "MR46404";
            public const string P3_ROJog_Plus = "MR46701";
            public const string P3_ROJog_Minus ="MR46702";
            public const string P3_ROHome =     "MR46700";
            public const string P3_ROReset =    "MR46705";
            public const string P3_ROGo_ABS =   "MR46703";
            public const string P3_ROGo_INC =   "MR46704";
            public const string P3_FJog_Plus =  "MR47001";
            public const string P3_FJog_Minus = "MR47002";
            public const string P3_FHome =      "MR47000";
            public const string P3_FReset =     "MR47005";
            public const string P3_FGo_ABS =    "MR47003";
            public const string P3_FGo_INC =    "MR47004";
            #endregion

            #region Port 4 Jog
            public const string P4_Step_Jog_Mode = "MR01002";
            public const string P4_XJog_Plus =  "MR41901";
            public const string P4_XJog_Minus = "MR41902";
            public const string P4_XHome =      "MR41900";
            public const string P4_XReset =     "MR41905";
            public const string P4_XGo_ABS =    "MR41903";
            public const string P4_XGo_INC =    "MR41904";
            public const string P4_YJog_Plus =  "MR42201";
            public const string P4_YJog_Minus = "MR42202";
            public const string P4_YHome =      "MR42200";
            public const string P4_YReset =     "MR42205";
            public const string P4_YGo_ABS =    "MR42203";
            public const string P4_YGo_INC =    "MR42204";
            public const string P4_ZJog_Plus =  "MR42501";
            public const string P4_ZJog_Minus = "MR42502";
            public const string P4_ZHome =      "MR42500";
            public const string P4_ZReset =     "MR42505";
            public const string P4_ZGo_ABS =    "MR42503";
            public const string P4_ZGo_INC =    "MR42504";
            public const string P4_RIJog_Plus = "MR42801";
            public const string P4_RIJog_Minus ="MR42802";
            public const string P4_RIHome =     "MR42800";
            public const string P4_RIReset =    "MR42805";
            public const string P4_RIGo_ABS =   "MR42803";
            public const string P4_RIGo_INC =   "MR42804";
            public const string P4_ROJog_Plus = "MR43101";
            public const string P4_ROJog_Minus ="MR43102";
            public const string P4_ROHome =     "MR43100";
            public const string P4_ROReset =    "MR43105";
            public const string P4_ROGo_ABS =   "MR43103";
            public const string P4_ROGo_INC =   "MR43104";
            public const string P4_FJog_Plus =  "MR43401";
            public const string P4_FJog_Minus = "MR43402";
            public const string P4_FHome =      "MR43400";
            public const string P4_FReset =     "MR43405";
            public const string P4_FGo_ABS =    "MR43403";
            public const string P4_FGo_INC =    "MR43404";
            #endregion
        }

        /// <summary>
        /// Địa chỉ Output (đầu ra)
        /// </summary>
        public static class Output
        {
            public const string Den_bao = "R500";
            public const string Dong_co_chinh = "R501";
            public const string Van_khi = "R502";
            public const string Gia_tri_dat = "DM500";

        }

        /// <summary>
        /// Địa chỉ Data (dữ liệu)
        /// </summary>
        public static class Data
        {
            // Master 
            public const string P1_X_Master = "DM2082";
            public const string P1_Y_Master = "DM2084";
            public const string P1_R_Master = "DM2086";

            public const string P2_X_Master = "DM1282";
            public const string P2_Y_Master = "DM1284";
            public const string P2_R_Master = "DM1286";

            public const string P3_X_Master = "DM2482";
            public const string P3_Y_Master = "DM2484";
            public const string P3_R_Master = "DM2486";

            public const string P4_X_Master = "DM1682";
            public const string P4_Y_Master = "DM1684";
            public const string P4_R_Master = "DM1686";

            // Port
            public const string P1_X_Pos_Cur =  "TM332";
            public const string P1_RI_Pos_Cur = "TM334";
            public const string P1_Y_Pos_Cur =  "TM336";
            public const string P1_RO_Pos_Cur = "TM338";
            public const string P1_Z_Pos_Cur =  "TM340";
            public const string P1_F_Pos_Cur =  "TM344";
            public const string P1_X_ABS_Setpoint =     "DM370";
            public const string P1_Y_ABS_Setpoint =     "DM400";
            public const string P1_RI_ABS_Setpoint =    "DM460";
            public const string P1_RI_INC_Setpoint =    "DM464";

            public const string P2_X_Pos_Cur =  "TM300";
            public const string P2_RI_Pos_Cur = "TM302";
            public const string P2_Y_Pos_Cur =  "TM304";
            public const string P2_RO_Pos_Cur = "TM306";
            public const string P2_Z_Pos_Cur =  "TM308";
            public const string P2_F_Pos_Cur =  "TM312";
            public const string P2_X_ABS_Setpoint =     "DM10";
            public const string P2_Y_ABS_Setpoint =     "DM40";
            public const string P2_RI_ABS_Setpoint =    "DM100";
            public const string P2_RI_INC_Setpoint =    "DM104";

            public const string P3_X_Pos_Cur =  "TM348";
            public const string P3_RI_Pos_Cur = "TM350";
            public const string P3_Y_Pos_Cur =  "TM352";
            public const string P3_RO_Pos_Cur = "TM354";
            public const string P3_Z_Pos_Cur =  "TM356";
            public const string P3_F_Pos_Cur =  "TM360";
            public const string P3_X_ABS_Setpoint =     "DM550";
            public const string P3_Y_ABS_Setpoint =     "DM580";
            public const string P3_RI_ABS_Setpoint =    "DM640";
            public const string P3_RI_INC_Setpoint =    "DM644";

            public const string P4_X_Pos_Cur =  "TM316";
            public const string P4_RI_Pos_Cur = "TM318";
            public const string P4_Y_Pos_Cur =  "TM320";
            public const string P4_RO_Pos_Cur = "TM322";
            public const string P4_Z_Pos_Cur =  "TM324";
            public const string P4_F_Pos_Cur =  "TM328";
            public const string P4_X_ABS_Setpoint =     "DM190";
            public const string P4_Y_ABS_Setpoint =     "DM220";
            public const string P4_RI_ABS_Setpoint =    "DM280";
            public const string P4_RI_INC_Setpoint =    "DM284";

        }

    }
}
