//------------------------------------------------------------------------------
// <auto-generated>
//     File này được tạo tự động từ PLCConfig.json
//     Thời gian: 2025-10-29 (Initial version)
//     KHÔNG CHỈNH SỬA TRỰC TIẾP FILE NÀY!
//
//     Để regenerate file này, chạy:
//     PLCConfigManager manager = new PLCConfigManager();
//     manager.LoadConfig("PLCConfig.json");
//     manager.GenerateAddressesFile("PLCAddresses.Generated.cs");
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom;

namespace PLCKeygen
{
    /// <summary>
    /// Địa chỉ PLC được generate tự động từ PLCConfig.json
    /// PLC: Keyence_PLC_Main (192.168.1.100:8501)
    /// </summary>
    public static class PLCAddresses
    {
        public const string PLCName = "Keyence_PLC_Main";
        public const string IPAddress = "192.168.1.100";
        public const int Port = 8501;

        /// <summary>
        /// Địa chỉ Input (đầu vào)
        /// </summary>
        public static class Input
        {
            #region Port 1 Jog
            public const string P1_Step_Jog_Mode =  "MR02002";
            public const string P1_XJog_Plus =  "MR43701";
            public const string P1_XJog_Minus = "MR43702";
            public const string P1_XHome =      "MR43700";
            public const string P1_XReset =     "MR43705";
            public const string P1_XGo_ABS =    "MR43703";
            public const string P1_XGo_INC =    "MR43704";
            public const string P1_YJog_Plus =  "MR44001";
            public const string P1_YJog_Minus = "MR44002";
            public const string P1_YHome =      "MR44000";
            public const string P1_YReset =     "MR44005";
            public const string P1_YGo_ABS =    "MR44003";
            public const string P1_YGo_INC =    "MR44004";
            public const string P1_ZJog_Plus =  "MR44301";
            public const string P1_ZJog_Minus = "MR44302";
            public const string P1_ZHome =      "MR44300";
            public const string P1_ZReset =     "MR44305";
            public const string P1_ZGo_ABS =    "MR44303";
            public const string P1_ZGo_INC =    "MR44304";
            public const string P1_RIJog_Plus = "MR44601";
            public const string P1_RIJog_Minus ="MR44602";
            public const string P1_RIHome =     "MR44600";
            public const string P1_RIReset =    "MR44605";
            public const string P1_RIGo_ABS =   "MR44603";
            public const string P1_RIGo_INC =   "MR44604";
            public const string P1_ROJog_Plus = "MR44901";
            public const string P1_ROJog_Minus ="MR44902";
            public const string P1_ROHome =     "MR44900";
            public const string P1_ROReset =    "MR44905";
            public const string P1_ROGo_ABS =   "MR44903";
            public const string P1_ROGo_INC =   "MR44904";
            public const string P1_FJog_Plus =  "MR45201";
            public const string P1_FJog_Minus = "MR45202";
            public const string P1_FHome =      "MR45200";
            public const string P1_FReset =     "MR45205";
            public const string P1_FGo_ABS =    "MR45203";
            public const string P1_FGo_INC =    "MR45204";
            public const string P1_Auto_Mode = "MR22200";
            #endregion

            #region Port 2 Jog
            public const string P2_Step_Jog_Mode = "MR00002";
            public const string P2_XJog_Plus =  "MR40101";
            public const string P2_XJog_Minus = "MR40102";
            public const string P2_XHome =      "MR40100";
            public const string P2_XReset =     "MR40105";
            public const string P2_XGo_ABS =    "MR40103";
            public const string P2_XGo_INC =    "MR40104";
            public const string P2_YJog_Plus =  "MR40401";
            public const string P2_YJog_Minus = "MR40402";
            public const string P2_YHome =      "MR40400";
            public const string P2_YReset =     "MR40405";
            public const string P2_YGo_ABS =    "MR40403";
            public const string P2_YGo_INC =    "MR40404";
            public const string P2_ZJog_Plus =  "MR40701";
            public const string P2_ZJog_Minus = "MR40702";
            public const string P2_ZHome =      "MR40700";
            public const string P2_ZReset =     "MR40705";
            public const string P2_ZGo_ABS =    "MR40703";
            public const string P2_ZGo_INC =    "MR40704";
            public const string P2_RIJog_Plus = "MR41001";
            public const string P2_RIJog_Minus ="MR41002";
            public const string P2_RIHome =     "MR41000";
            public const string P2_RIReset =    "MR41005";
            public const string P2_RIGo_ABS =   "MR41003";
            public const string P2_RIGo_INC =   "MR41004";
            public const string P2_ROJog_Plus = "MR41301";
            public const string P2_ROJog_Minus ="MR41302";
            public const string P2_ROHome =     "MR41300";
            public const string P2_ROReset =    "MR41305";
            public const string P2_ROGo_ABS =   "MR41303";
            public const string P2_ROGo_INC =   "MR41304";
            public const string P2_FJog_Plus =  "MR41601";
            public const string P2_FJog_Minus = "MR41602";
            public const string P2_FHome =      "MR41600";
            public const string P2_FReset =     "MR41605";
            public const string P2_FGo_ABS =    "MR41603";
            public const string P2_FGo_INC =    "MR41604";
            public const string P2_Auto_Mode = "MR14200";
            #endregion

            #region Port 3 Jog
            public const string P3_Step_Jog_Mode = "MR03002";
            public const string P3_XJog_Plus =  "MR45501";
            public const string P3_XJog_Minus = "MR45502";
            public const string P3_XHome =      "MR45500";
            public const string P3_XReset =     "MR45505";
            public const string P3_XGo_ABS =    "MR45503";
            public const string P3_XGo_INC =    "MR45504";
            public const string P3_YJog_Plus =  "MR45801";
            public const string P3_YJog_Minus = "MR45802";
            public const string P3_YHome =      "MR45800";
            public const string P3_YReset =     "MR45805";
            public const string P3_YGo_ABS =    "MR45803";
            public const string P3_YGo_INC =    "MR45804";
            public const string P3_ZJog_Plus =  "MR46101";
            public const string P3_ZJog_Minus = "MR46102";
            public const string P3_ZHome =      "MR46100";
            public const string P3_ZReset =     "MR46105";
            public const string P3_ZGo_ABS =    "MR46103";
            public const string P3_ZGo_INC =    "MR46104";
            public const string P3_RIJog_Plus = "MR46401";
            public const string P3_RIJog_Minus ="MR46402";
            public const string P3_RIHome =     "MR46400";
            public const string P3_RIReset =    "MR46405";
            public const string P3_RIGo_ABS =   "MR46403";
            public const string P3_RIGo_INC =   "MR46404";
            public const string P3_ROJog_Plus = "MR46701";
            public const string P3_ROJog_Minus ="MR46702";
            public const string P3_ROHome =     "MR46700";
            public const string P3_ROReset =    "MR46705";
            public const string P3_ROGo_ABS =   "MR46703";
            public const string P3_ROGo_INC =   "MR46704";
            public const string P3_FJog_Plus =  "MR47001";
            public const string P3_FJog_Minus = "MR47002";
            public const string P3_FHome =      "MR47000";
            public const string P3_FReset =     "MR47005";
            public const string P3_FGo_ABS =    "MR47003";
            public const string P3_FGo_INC =    "MR47004";
            public const string P3_Auto_Mode = "MR26200";
            #endregion

            #region Port 4 Jog
            public const string P4_Step_Jog_Mode = "MR01002";
            public const string P4_XJog_Plus =  "MR41901";
            public const string P4_XJog_Minus = "MR41902";
            public const string P4_XHome =      "MR41900";
            public const string P4_XReset =     "MR41905";
            public const string P4_XGo_ABS =    "MR41903";
            public const string P4_XGo_INC =    "MR41904";
            public const string P4_YJog_Plus =  "MR42201";
            public const string P4_YJog_Minus = "MR42202";
            public const string P4_YHome =      "MR42200";
            public const string P4_YReset =     "MR42205";
            public const string P4_YGo_ABS =    "MR42203";
            public const string P4_YGo_INC =    "MR42204";
            public const string P4_ZJog_Plus =  "MR42501";
            public const string P4_ZJog_Minus = "MR42502";
            public const string P4_ZHome =      "MR42500";
            public const string P4_ZReset =     "MR42505";
            public const string P4_ZGo_ABS =    "MR42503";
            public const string P4_ZGo_INC =    "MR42504";
            public const string P4_RIJog_Plus = "MR42801";
            public const string P4_RIJog_Minus ="MR42802";
            public const string P4_RIHome =     "MR42800";
            public const string P4_RIReset =    "MR42805";
            public const string P4_RIGo_ABS =   "MR42803";
            public const string P4_RIGo_INC =   "MR42804";
            public const string P4_ROJog_Plus = "MR43101";
            public const string P4_ROJog_Minus ="MR43102";
            public const string P4_ROHome =     "MR43100";
            public const string P4_ROReset =    "MR43105";
            public const string P4_ROGo_ABS =   "MR43103";
            public const string P4_ROGo_INC =   "MR43104";
            public const string P4_FJog_Plus =  "MR43401";
            public const string P4_FJog_Minus = "MR43402";
            public const string P4_FHome =      "MR43400";
            public const string P4_FReset =     "MR43405";
            public const string P4_FGo_ABS =    "MR43403";
            public const string P4_FGo_INC =    "MR43404";
            public const string P4_Auto_Mode = "MR18200";
            #endregion

            #region Port 1 Limit Switches

            // X Axis Limits
            /// <summary>X Axis - Limit Plus</summary>
            public const string P1_X_LimitPlus = "DM388.0";
            /// <summary>X Axis - Home</summary>
            public const string P1_X_Home = "DM388.2";
            /// <summary>X Axis - Limit Minus</summary>
            public const string P1_X_LimitMinus = "DM388.1";

            // Y Axis Limits
            /// <summary>Y Axis - Limit Plus</summary>
            public const string P1_Y_LimitPlus = "DM418.0";
            /// <summary>Y Axis - Home</summary>
            public const string P1_Y_Home = "DM418.2";
            /// <summary>Y Axis - Limit Minus</summary>
            public const string P1_Y_LimitMinus = "DM418.1";

            // Z Axis Limits
            /// <summary>Z Axis - Limit Plus</summary>
            public const string P1_Z_LimitPlus = "DM448.0";
            /// <summary>Z Axis - Home</summary>
            public const string P1_Z_Home = "DM448.2";
            /// <summary>Z Axis - Limit Minus</summary>
            public const string P1_Z_LimitMinus = "DM448.1";

            // F Axis Limits
            /// <summary>F Axis - Limit Plus</summary>
            public const string P1_F_LimitPlus = "DM538.0";
            /// <summary>F Axis - Home</summary>
            public const string P1_F_Home = "DM538.2";
            /// <summary>F Axis - Limit Minus</summary>
            public const string P1_F_LimitMinus = "DM538.1";

            #endregion

            #region Port 1 Control Signals

            /// <summary>Motor Disable</summary>
            public const string P1_Motor_Disable = "MR2007";

            /// <summary>Bypass Door</summary>
            public const string P1_Bypass_Door = "MR2011";

            /// <summary>Dry Run Mode</summary>
            public const string P1_Dry_Run_Mode = "MR2010";

            /// <summary>Bypass Sensor Detect Tray</summary>
            public const string P1_Bypass_Sensor_Detect_Tray = "MR2012";

            #endregion

            #region Port 1 I/O Sensors (MR21, MR22)

            // ===== MR21 Register =====
            /// <summary>Sensor: Input - Ss VIn1</summary>
            public const string P1_Ss_VIn1 = "MR2100";

            /// <summary>Sensor: Output - Ss VOt1</summary>
            public const string P1_Ss_VOt1 = "MR2101";

            /// <summary>Sensor: Camera Port 1 Vacuum - Ss VCa21 Port1</summary>
            public const string P1_Ss_VCa21_Port1 = "MR2102";

            /// <summary>Sensor: Camera Port 2 Vacuum - Ss VCa21 Port2</summary>
            public const string P1_Ss_VCa21_Port2 = "MR2103";

            /// <summary>Sensor: Fixture Open - Ss Fix1 Open</summary>
            public const string P1_Ss_Fix1_Open = "MR2104";

            /// <summary>Sensor: Fixture Close - Ss Fix1 Close</summary>
            public const string P1_Ss_Fix1_Close = "MR2105";

            /// <summary>Status: Tower Light Start - Stt lca Start1</summary>
            public const string P1_Stt_lca_Start1 = "MR2106";

            /// <summary>Status: Tower Light Stop - Stt lca Stop1</summary>
            public const string P1_Stt_lca_Stop1 = "MR2107";

            /// <summary>Status: Tower Light Green - Stt lca Gre1</summary>
            public const string P1_Stt_lca_Gre1 = "MR2108";

            /// <summary>Status: Tower Light Yellow - Stt lca Yel1</summary>
            public const string P1_Stt_lca_Yel1 = "MR2109";

            /// <summary>Status: Tower Light Red - Stt lca Red1</summary>
            public const string P1_Stt_lca_Red1 = "MR2110";

            /// <summary>Sensor: Door 1 - Ss Door1</summary>
            public const string P1_Ss_Door1 = "MR2111";

            /// <summary>Sensor: Jig OK - Ss Jig OK</summary>
            public const string P1_Ss_Jig_OK = "MR2112";

            /// <summary>Sensor: Tray OK - Ss Tray OK</summary>
            public const string P1_Ss_Tray_OK = "MR2113";

            /// <summary>Sensor: Jig NG - Ss Jig NG</summary>
            public const string P1_Ss_Jig_NG = "MR2114";

            /// <summary>Sensor: Tray NG - Ss Tray NG</summary>
            public const string P1_Ss_Tray_NG = "MR2115";

            // ===== MR22 Register =====
            /// <summary>Sensor: Jig NG4 - Ss Jig NG4</summary>
            public const string P1_Ss_Jig_NG4 = "MR2200";

            /// <summary>Sensor: Tray NG4 - Ss Tray NG4</summary>
            public const string P1_Ss_Tray_NG4 = "MR2201";

            /// <summary>Switch: Emergency Stop 1 - SW EMS1</summary>
            public const string P1_SW_EMS1 = "MR2202";

            /// <summary>Switch: Start 1 - SW Start1</summary>
            public const string P1_SW_Start1 = "MR2203";

            /// <summary>Switch: Stop 1 - SW Stop1</summary>
            public const string P1_SW_Stop1 = "MR2204";

            /// <summary>Switch: Reset 1 - SW Reset1</summary>
            public const string P1_SW_Reset1 = "MR2205";

            /// <summary>Sensor: Air Positive 1 - Ss Air+1</summary>
            public const string P1_Ss_AirPlus1 = "MR2206";

            /// <summary>Sensor: Air Negative 1 - Ss Air-1</summary>
            public const string P1_Ss_AirMinus1 = "MR2207";

            /// <summary>Sensor: Vision Seek 1 - Ss VSk1</summary>
            public const string P1_Ss_VSk1 = "MR2208";

            /// <summary>Switch: Initialize 1 - SW Init1</summary>
            public const string P1_SW_Init1 = "MR2209";

            /// <summary>Switch: Initialize 1 - SW Init1</summary>
            public const string P1_Chart_On = "MR2210";

            /// <summary>Switch: Initialize 1 - SW Init1</summary>
            public const string P1_Chart_Off = "MR2211";

            #endregion

            #region Port 2 Limit Switches

            // X Axis Limits
            /// <summary>X Axis - Limit Plus</summary>
            public const string P2_X_LimitPlus = "DM28.0";
            /// <summary>X Axis - Home</summary>
            public const string P2_X_Home = "DM28.2";
            /// <summary>X Axis - Limit Minus</summary>
            public const string P2_X_LimitMinus = "DM28.1";

            // Y Axis Limits
            /// <summary>Y Axis - Limit Plus</summary>
            public const string P2_Y_LimitPlus = "DM58.0";
            /// <summary>Y Axis - Home</summary>
            public const string P2_Y_Home = "DM58.2";
            /// <summary>Y Axis - Limit Minus</summary>
            public const string P2_Y_LimitMinus = "DM58.1";

            // Z Axis Limits
            /// <summary>Z Axis - Limit Plus</summary>
            public const string P2_Z_LimitPlus = "DM88.0";
            /// <summary>Z Axis - Home</summary>
            public const string P2_Z_Home = "DM88.2";
            /// <summary>Z Axis - Limit Minus</summary>
            public const string P2_Z_LimitMinus = "DM88.1";

            // F Axis Limits
            /// <summary>F Axis - Limit Plus</summary>
            public const string P2_F_LimitPlus = "DM178.0";
            /// <summary>F Axis - Home</summary>
            public const string P2_F_Home = "DM178.2";
            /// <summary>F Axis - Limit Minus</summary>
            public const string P2_F_LimitMinus = "DM178.1";

            #endregion

            #region Port 2 Control Signals

            /// <summary>Motor Disable</summary>
            public const string P2_Motor_Disable = "MR007";

            /// <summary>Bypass Door</summary>
            public const string P2_Bypass_Door = "MR011";

            /// <summary>Dry Run Mode</summary>
            public const string P2_Dry_Run_Mode = "MR10";

            /// <summary>Bypass Sensor Detect Tray</summary>
            public const string P2_Bypass_Sensor_Detect_Tray = "MR012";

            #endregion

            #region Port 2 I/O Sensors (MR1, MR2)

            // ===== MR1 Register =====
            /// <summary>Sensor: Input - Ss VIn2</summary>
            public const string P2_Ss_VIn2 = "MR100";

            /// <summary>Sensor: Output - Ss VOt2</summary>
            public const string P2_Ss_VOt2 = "MR101";

            /// <summary>Sensor: Camera Port 2 Vacuum - Ss VCa12 Port2</summary>
            public const string P2_Ss_VCa12_Port2 = "MR102";

            /// <summary>Sensor: Camera Port 1 Vacuum - Ss VCa12 Port1</summary>
            public const string P2_Ss_VCa12_Port1 = "MR103";

            /// <summary>Sensor: Fixture 2 Open - Ss Fix2 Open</summary>
            public const string P2_Ss_Fix2_Open = "MR104";

            /// <summary>Sensor: Fixture 2 Close - Ss Fix2 Close</summary>
            public const string P2_Ss_Fix2_Close = "MR105";

            /// <summary>Status: Tower Light Start 2 / StatusTester - Stt lca Start2</summary>
            public const string P2_Stt_lca_Start2_StatusTester = "MR106";

            /// <summary>Status: Tower Light Stop 2 / StatusTester - Stt lca Stop2</summary>
            public const string P2_Stt_lca_Stop2_StatusTester = "MR107";

            /// <summary>Status: Tower Light Green 2 - Stt lca Gre2</summary>
            public const string P2_Stt_lca_Gre2 = "MR108";

            /// <summary>Status: Tower Light Yellow 2 - Stt lca Yel2</summary>
            public const string P2_Stt_lca_Yel2 = "MR109";

            /// <summary>Status: Tower Light Red 2 - Stt lca Red2</summary>
            public const string P2_Stt_lca_Red2 = "MR110";

            /// <summary>Sensor: Door 2 - Ss Door2</summary>
            public const string P2_Ss_Door2 = "MR111";

            /// <summary>Sensor: Jig OK - Ss Jig OK</summary>
            public const string P2_Ss_Jig_OK = "MR112";

            /// <summary>Sensor: Tray OK - Ss Tray OK</summary>
            public const string P2_Ss_Tray_OK = "MR113";

            /// <summary>Sensor: Jig NG - Ss Jig NG</summary>
            public const string P2_Ss_Jig_NG = "MR114";

            /// <summary>Sensor: Tray NG - Ss Tray NG</summary>
            public const string P2_Ss_Tray_NG = "MR115";

            // ===== MR2 Register =====
            /// <summary>Sensor: Jig NG4 - Ss Jig NG4</summary>
            public const string P2_Ss_Jig_NG4 = "MR200";

            /// <summary>Sensor: Tray NG4 - Ss Tray NG4</summary>
            public const string P2_Ss_Tray_NG4 = "MR201";

            /// <summary>Switch: Emergency Stop 2 - SW EMS2</summary>
            public const string P2_SW_EMS2 = "MR202";

            /// <summary>Switch: Start 2 - SW Start2</summary>
            public const string P2_SW_Start2 = "MR203";

            /// <summary>Switch: Stop 2 - SW Stop2</summary>
            public const string P2_SW_Stop2 = "MR204";

            /// <summary>Switch: Reset 2 - SW Reset2</summary>
            public const string P2_SW_Reset2 = "MR205";

            /// <summary>Sensor: Air Positive 2 - Ss Air+2</summary>
            public const string P2_Ss_AirPlus2 = "MR206";

            /// <summary>Sensor: Air Negative 2 - Ss Air-2</summary>
            public const string P2_Ss_AirMinus2 = "MR207";

            /// <summary>Sensor: Vision Seek 2 - Ss VSk2</summary>
            public const string P2_Ss_VSk2 = "MR208";

            /// <summary>Switch: Initialize 2 - SW Init2</summary>
            public const string P2_SW_Init2 = "MR209";

            /// <summary>Switch: Initialize 1 - SW Init1</summary>
            public const string P2_Chart_On = "MR210";

            /// <summary>Switch: Initialize 1 - SW Init1</summary>
            public const string P2_Chart_Off = "MR211";

            #endregion

            #region Port 3 Limit Switches

            // X Axis Limits
            /// <summary>X Axis - Limit Plus</summary>
            public const string P3_X_LimitPlus = "DM568.0";
            /// <summary>X Axis - Home</summary>
            public const string P3_X_Home = "DM568.2";
            /// <summary>X Axis - Limit Minus</summary>
            public const string P3_X_LimitMinus = "DM568.1";

            // Y Axis Limits
            /// <summary>Y Axis - Limit Plus</summary>
            public const string P3_Y_LimitPlus = "DM598.0";
            /// <summary>Y Axis - Home</summary>
            public const string P3_Y_Home = "DM598.2";
            /// <summary>Y Axis - Limit Minus</summary>
            public const string P3_Y_LimitMinus = "DM598.1";

            // Z Axis Limits
            /// <summary>Z Axis - Limit Plus</summary>
            public const string P3_Z_LimitPlus = "DM628.0";
            /// <summary>Z Axis - Home</summary>
            public const string P3_Z_Home = "DM628.2";
            /// <summary>Z Axis - Limit Minus</summary>
            public const string P3_Z_LimitMinus = "DM628.1";

            // F Axis Limits
            /// <summary>F Axis - Limit Plus</summary>
            public const string P3_F_LimitPlus = "DM718.0";
            /// <summary>F Axis - Home</summary>
            public const string P3_F_Home = "DM718.2";
            /// <summary>F Axis - Limit Minus</summary>
            public const string P3_F_LimitMinus = "DM718.1";

            #endregion

            #region Port 3 Control Signals

            /// <summary>Motor Disable</summary>
            public const string P3_Motor_Disable = "MR3007";

            /// <summary>Bypass Door</summary>
            public const string P3_Bypass_Door = "MR3011";

            /// <summary>Dry Run Mode</summary>
            public const string P3_Dry_Run_Mode = "MR3010";

            /// <summary>Bypass Sensor Detect Tray</summary>
            public const string P3_Bypass_Sensor_Detect_Tray = "MR3012";

            #endregion

            #region Port 3 I/O Sensors (MR31, MR32)

            // ===== MR31 Register =====
            /// <summary>Sensor: Input - Ss VIn3</summary>
            public const string P3_Ss_VIn3 = "MR3100";

            /// <summary>Sensor: Output - Ss VOt3</summary>
            public const string P3_Ss_VOt3 = "MR3101";

            /// <summary>Sensor: Camera Port 3 Vacuum - Ss VCa34 Port3</summary>
            public const string P3_Ss_VCa34_Port3 = "MR3102";

            /// <summary>Sensor: Camera Port 4 Vacuum - Ss VCa34 Port4</summary>
            public const string P3_Ss_VCa34_Port4 = "MR3103";

            /// <summary>Sensor: Fixture 3 Open - Ss Fix3 Open</summary>
            public const string P3_Ss_Fix3_Open = "MR3104";

            /// <summary>Sensor: Fixture 3 Close - Ss Fix3 Close</summary>
            public const string P3_Ss_Fix3_Close = "MR3105";

            /// <summary>Status: Tower Light Start 3 - Stt lca Start3</summary>
            public const string P3_Stt_lca_Start3 = "MR3106";

            /// <summary>Status: Tower Light Stop 3 - Stt lca Stop3</summary>
            public const string P3_Stt_lca_Stop3 = "MR3107";

            /// <summary>Status: Tower Light Green 3 - Stt lca Gre3</summary>
            public const string P3_Stt_lca_Gre3 = "MR3108";

            /// <summary>Status: Tower Light Yellow 3 - Stt lca Yel3</summary>
            public const string P3_Stt_lca_Yel3 = "MR3109";

            /// <summary>Status: Tower Light Red 3 - Stt lca Red3</summary>
            public const string P3_Stt_lca_Red3 = "MR3110";

            /// <summary>Sensor: Door 3 - Ss Door3</summary>
            public const string P3_Ss_Door3 = "MR3111";

            /// <summary>Sensor: Jig OK - Ss Jig OK</summary>
            public const string P3_Ss_Jig_OK = "MR3112";

            /// <summary>Sensor: Tray OK - Ss Tray OK</summary>
            public const string P3_Ss_Tray_OK = "MR3113";

            /// <summary>Sensor: Jig NG - Ss Jig NG</summary>
            public const string P3_Ss_Jig_NG = "MR3114";

            /// <summary>Sensor: Tray NG - Ss Tray NG</summary>
            public const string P3_Ss_Tray_NG = "MR3115";

            // ===== MR32 Register =====
            /// <summary>Sensor: Jig NG4 - Ss Jig NG4</summary>
            public const string P3_Ss_Jig_NG4 = "MR3200";

            /// <summary>Sensor: Tray NG4 - Ss Tray NG4</summary>
            public const string P3_Ss_Tray_NG4 = "MR3201";

            /// <summary>Switch: Emergency Stop 3 - SW EMS3</summary>
            public const string P3_SW_EMS3 = "MR3202";

            /// <summary>Switch: Start 3 - SW Start3</summary>
            public const string P3_SW_Start3 = "MR3203";

            /// <summary>Switch: Stop 3 - SW Stop3</summary>
            public const string P3_SW_Stop3 = "MR3204";

            /// <summary>Switch: Reset 3 - SW Reset3</summary>
            public const string P3_SW_Reset3 = "MR3205";

            /// <summary>Sensor: Air Positive 3 - Ss Air+3</summary>
            public const string P3_Ss_AirPlus3 = "MR3206";

            /// <summary>Sensor: Air Negative 3 - Ss Air-3</summary>
            public const string P3_Ss_AirMinus3 = "MR3207";

            /// <summary>Sensor: Vision Seek 3 - Ss VSk3</summary>
            public const string P3_Ss_VSk3 = "MR3208";

            /// <summary>Switch: Initialize 3 - SW Init3</summary>
            public const string P3_SW_Init3 = "MR3209";

            /// <summary>Switch: Initialize 1 - SW Init1</summary>
            public const string P3_Chart_On = "MR3210";

            /// <summary>Switch: Initialize 1 - SW Init1</summary>
            public const string P3_Chart_Off = "MR3211";

            #endregion

            #region Port 4 Limit Switches

            // X Axis Limits
            /// <summary>X Axis - Limit Plus</summary>
            public const string P4_X_LimitPlus = "DM208.0";
            /// <summary>X Axis - Home</summary>
            public const string P4_X_Home = "DM208.2";
            /// <summary>X Axis - Limit Minus</summary>
            public const string P4_X_LimitMinus = "DM208.1";

            // Y Axis Limits
            /// <summary>Y Axis - Limit Plus</summary>
            public const string P4_Y_LimitPlus = "DM238.0";
            /// <summary>Y Axis - Home</summary>
            public const string P4_Y_Home = "DM238.2";
            /// <summary>Y Axis - Limit Minus</summary>
            public const string P4_Y_LimitMinus = "DM238.1";

            // Z Axis Limits
            /// <summary>Z Axis - Limit Plus</summary>
            public const string P4_Z_LimitPlus = "DM268.0";
            /// <summary>Z Axis - Home</summary>
            public const string P4_Z_Home = "DM268.2";
            /// <summary>Z Axis - Limit Minus</summary>
            public const string P4_Z_LimitMinus = "DM268.1";

            // F Axis Limits
            /// <summary>F Axis - Limit Plus</summary>
            public const string P4_F_LimitPlus = "DM358.0";
            /// <summary>F Axis - Home</summary>
            public const string P4_F_Home = "DM358.2";
            /// <summary>F Axis - Limit Minus</summary>
            public const string P4_F_LimitMinus = "DM358.1";

            #endregion

            #region Port 4 Control Signals

            /// <summary>Motor Disable</summary>
            public const string P4_Motor_Disable = "MR1007";

            /// <summary>Bypass Door</summary>
            public const string P4_Bypass_Door = "MR1011";

            /// <summary>Dry Run Mode</summary>
            public const string P4_Dry_Run_Mode = "MR1010";

            /// <summary>Bypass Sensor Detect Tray</summary>
            public const string P4_Bypass_Sensor_Detect_Tray = "MR1012";

            #endregion

            #region Port 4 I/O Sensors (MR11, MR12)

            // ===== MR11 Register =====
            /// <summary>Sensor: Input - Ss VIn4</summary>
            public const string P4_Ss_VIn4 = "MR1100";

            /// <summary>Sensor: Output - Ss VOt24</summary>
            public const string P4_Ss_VOt24 = "MR1101";

            /// <summary>Sensor: Camera Port 4 Vacuum - Ss VCa34 Port4</summary>
            public const string P4_Ss_VCa34_Port4 = "MR1102";

            /// <summary>Sensor: Camera Port 3 Vacuum - Ss VCa34 Port3</summary>
            public const string P4_Ss_VCa34_Port3 = "MR1103";

            /// <summary>Sensor: Fixture 4 Open - Ss Fix4 Open</summary>
            public const string P4_Ss_Fix4_Open = "MR1104";

            /// <summary>Sensor: Fixture 4 Close - Ss Fix4 Close</summary>
            public const string P4_Ss_Fix4_Close = "MR1105";

            /// <summary>Status: Tower Light Start 4 - Stt lca Start4</summary>
            public const string P4_Stt_lca_Start4 = "MR1106";

            /// <summary>Status: Tower Light Stop 4 - Stt lca Stop4</summary>
            public const string P4_Stt_lca_Stop4 = "MR1107";

            /// <summary>Status: Tower Light Green 4 - Stt lca Gre4</summary>
            public const string P4_Stt_lca_Gre4 = "MR1108";

            /// <summary>Status: Tower Light Yellow 4 - Stt lca Yel4</summary>
            public const string P4_Stt_lca_Yel4 = "MR1109";

            /// <summary>Status: Tower Light Red 4 - Stt lca Red4</summary>
            public const string P4_Stt_lca_Red4 = "MR1110";

            /// <summary>Sensor: Door 4 - Ss Door4</summary>
            public const string P4_Ss_Door4 = "MR1111";

            /// <summary>Sensor: Jig OK - Ss Jig OK</summary>
            public const string P4_Ss_Jig_OK = "MR1112";

            /// <summary>Sensor: Tray OK - Ss Tray OK</summary>
            public const string P4_Ss_Tray_OK = "MR1113";

            /// <summary>Sensor: Jig NG - Ss Jig NG</summary>
            public const string P4_Ss_Jig_NG = "MR1114";

            /// <summary>Sensor: Tray NG - Ss Tray NG</summary>
            public const string P4_Ss_Tray_NG = "MR1115";

            // ===== MR12 Register =====
            /// <summary>Sensor: Jig NG4 - Ss Jig NG4</summary>
            public const string P4_Ss_Jig_NG4 = "MR1200";

            /// <summary>Sensor: Tray NG4 - Ss Tray NG4</summary>
            public const string P4_Ss_Tray_NG4 = "MR1201";

            /// <summary>Switch: Emergency Stop 4 - SW EMS4</summary>
            public const string P4_SW_EMS4 = "MR1202";

            /// <summary>Switch: Start 4 - SW Start4</summary>
            public const string P4_SW_Start4 = "MR1203";

            /// <summary>Switch: Stop 4 - SW Stop4</summary>
            public const string P4_SW_Stop4 = "MR1204";

            /// <summary>Switch: Reset 4 - SW Reset4</summary>
            public const string P4_SW_Reset4 = "MR1205";

            /// <summary>Sensor: Air Positive 4 - Ss Air+4</summary>
            public const string P4_Ss_AirPlus4 = "MR1206";

            /// <summary>Sensor: Air Negative 4 - Ss Air-4</summary>
            public const string P4_Ss_AirMinus4 = "MR1207";

            /// <summary>Sensor: Vision Seek 4 - Ss VSk4</summary>
            public const string P4_Ss_VSk4 = "MR1208";

            /// <summary>Switch: Initialize 4 - SW Init4</summary>
            public const string P4_SW_Init4 = "MR1209";

            /// <summary>Switch: Initialize 1 - SW Init1</summary>
            public const string P4_Chart_On = "MR1210";

            /// <summary>Switch: Initialize 1 - SW Init1</summary>
            public const string P4_Chart_Off = "MR1211";

            #endregion
        }

        /// <summary>
        /// Địa chỉ Output (đầu ra)
        /// </summary>
        public static class Output
        {
            #region Camera Cylinders
            /// <summary>Xi lanh camera Port 1-2</summary>
            public const string P12_Cam_cylinder = "MR5002";

            /// <summary>Xi lanh camera Port 3-4</summary>
            public const string P34_Cam_cylinder = "MR6002";
            #endregion

            #region Port 1
            public const string P1_Home_All_Request = "MR21400";
            public const string P1_Reset_All_Request = "MR21401";
            public const string P1_Cylinder_Vaccum_Load = "MR7000";
            public const string P1_Cylinder_Vaccum_Unload = "MR7001";
            public const string P1_Request_Camera = "MR7002";
            public const string P1_Cylinder_Fix_Socket = "MR7003";
            public const string P1_LCA_Request_Init = "MR7004";
            public const string P1_LCA_Request_Start = "MR7005";
            public const string P1_LCA_Request_Stop = "MR7006";
            public const string P1_LCA_Request_Reset = "MR7007";
            public const string P1_Cylinder_Chart_Socket = "MR7014";
            public const string P1_Driver_Disable = "MR2202";
            #endregion

            #region Port 2
            public const string P2_Home_All_Request = "MR13400";
            public const string P2_Reset_All_Request = "MR13401";
            public const string P2_Cylinder_Vaccum_Load = "MR5000";
            public const string P2_Cylinder_Vaccum_Unload = "MR5001";
            public const string P2_Request_Camera = "MR5002";
            public const string P2_Cylinder_Fix_Socket = "MR5003";
            public const string P2_LCA_Request_Init = "MR5004";
            public const string P2_LCA_Request_Start = "MR5005";
            public const string P2_LCA_Request_Stop = "MR5006";
            public const string P2_LCA_Request_Reset = "MR5007";
            public const string P2_Cylinder_Chart_Socket = "MR5014";
            public const string P2_Driver_Disable = "MR202";
            #endregion

            #region Port 3
            public const string P3_Home_All_Request = "MR25400";
            public const string P3_Reset_All_Request = "MR25401";
            public const string P3_Cylinder_Vaccum_Load = "MR8000";
            public const string P3_Cylinder_Vaccum_Unload = "MR8001";
            public const string P3_Request_Camera = "MR8002";
            public const string P3_Cylinder_Fix_Socket = "MR8003";
            public const string P3_LCA_Request_Init = "MR8004";
            public const string P3_LCA_Request_Start = "MR8005";
            public const string P3_LCA_Request_Stop = "MR8006";
            public const string P3_LCA_Request_Reset = "MR8007";
            public const string P3_Cylinder_Chart_Socket = "MR8014";
            public const string P3_Driver_Disable = "MR3202";
            #endregion

            #region Port 4
            public const string P4_Home_All_Request = "MR17400";
            public const string P4_Reset_All_Request = "MR17401";
            public const string P4_Cylinder_Vaccum_Load = "MR6000";
            public const string P4_Cylinder_Vaccum_Unload = "MR6001";
            public const string P4_Request_Camera = "MR6002";
            public const string P4_Cylinder_Fix_Socket = "MR6003";
            public const string P4_LCA_Request_Init = "MR6004";
            public const string P4_LCA_Request_Start = "MR6005";
            public const string P4_LCA_Request_Stop = "MR6006";
            public const string P4_LCA_Request_Reset = "MR6007";
            public const string P4_Cylinder_Chart_Socket = "MR6014";
            public const string P4_Driver_Disable = "MR1202";
            #endregion

        }

        /// <summary>
        /// Địa chỉ Data (dữ liệu)
        /// </summary>
        public static class Data
        {

            // Port1
            public const string P1_X_Pos_Cur =  "TM332";
            public const string P1_RI_Pos_Cur = "TM334";
            public const string P1_Y_Pos_Cur =  "TM336";
            public const string P1_RO_Pos_Cur = "TM338";
            public const string P1_Z_Pos_Cur =  "TM340";
            public const string P1_F_Pos_Cur =  "TM344";
            public const string P1_X_ABS_Setpoint =     "DM370";
            public const string P1_Y_ABS_Setpoint =     "DM400";
            public const string P1_RI_ABS_Setpoint =    "DM460";
            public const string P1_RI_INC_Setpoint =    "DM464";
            public const string P1_X_Master = "DM2082";
            public const string P1_Y_Master = "DM2084";
            public const string P1_R_Master = "DM2086";
            // Port2
            public const string P2_X_Pos_Cur =  "TM300";
            public const string P2_RI_Pos_Cur = "TM302";
            public const string P2_Y_Pos_Cur =  "TM304";
            public const string P2_RO_Pos_Cur = "TM306";
            public const string P2_Z_Pos_Cur =  "TM308";
            public const string P2_F_Pos_Cur =  "TM312";
            public const string P2_X_ABS_Setpoint =     "DM10";
            public const string P2_Y_ABS_Setpoint =     "DM40";
            public const string P2_RI_ABS_Setpoint =    "DM100";
            public const string P2_RI_INC_Setpoint =    "DM104";
            public const string P2_X_Master = "DM1282";
            public const string P2_Y_Master = "DM1284";
            public const string P2_R_Master = "DM1286";
            // Port3
            public const string P3_X_Pos_Cur =  "TM348";
            public const string P3_RI_Pos_Cur = "TM350";
            public const string P3_Y_Pos_Cur =  "TM352";
            public const string P3_RO_Pos_Cur = "TM354";
            public const string P3_Z_Pos_Cur =  "TM356";
            public const string P3_F_Pos_Cur =  "TM360";
            public const string P3_X_ABS_Setpoint =     "DM550";
            public const string P3_Y_ABS_Setpoint =     "DM580";
            public const string P3_RI_ABS_Setpoint =    "DM640";
            public const string P3_RI_INC_Setpoint =    "DM644";
            public const string P3_X_Master = "DM2482";
            public const string P3_Y_Master = "DM2484";
            public const string P3_R_Master = "DM2486";
            // Port4
            public const string P4_X_Pos_Cur =  "TM316";
            public const string P4_RI_Pos_Cur = "TM318";
            public const string P4_Y_Pos_Cur =  "TM320";
            public const string P4_RO_Pos_Cur = "TM322";
            public const string P4_Z_Pos_Cur =  "TM324";
            public const string P4_F_Pos_Cur =  "TM328";
            public const string P4_X_ABS_Setpoint =     "DM190";
            public const string P4_Y_ABS_Setpoint =     "DM220";
            public const string P4_RI_ABS_Setpoint =    "DM280";
            public const string P4_RI_INC_Setpoint =    "DM284";
            public const string P4_X_Master = "DM1682";
            public const string P4_Y_Master = "DM1684";
            public const string P4_R_Master = "DM1686";

            #region Port 1 Extended Data (Base: DM360-510, DM2000-2100, DM1800-1910)

            // Axis configuration data - Columns: DM360, DM390, DM420, DM450, DM480, DM510
            // Row 0: Timeout
            public const string P1_Timeout_X = "DM360";
            public const string P1_Timeout_Y = "DM390";
            public const string P1_Timeout_Z = "DM420";
            public const string P1_Timeout_F = "DM510";

            // Row 2: Dis Step Jog+
            public const string P1_DisStep_JogPlus_X = "DM362";
            public const string P1_DisStep_JogPlus_Y = "DM392";
            public const string P1_DisStep_JogPlus_Z = "DM422";
            public const string P1_DisStep_JogPlus_RI = "DM452";
            public const string P1_DisStep_JogPlus_RO = "DM482";
            public const string P1_DisStep_JogPlus_F = "DM512";

            // Row 4: Speed LJog
            public const string P1_Speed_LJog_X = "DM364";
            public const string P1_Speed_LJog_Y = "DM394";
            public const string P1_Speed_LJog_Z = "DM424";
            public const string P1_Speed_LJog_RI = "DM454";
            public const string P1_Speed_LJog_RO = "DM484";
            public const string P1_Speed_LJog_F = "DM514";

            // Row 6: Speed HJog
            public const string P1_Speed_HJog_X = "DM366";
            public const string P1_Speed_HJog_Y = "DM396";
            public const string P1_Speed_HJog_Z = "DM426";
            public const string P1_Speed_HJog_RI = "DM456";
            public const string P1_Speed_HJog_RO = "DM486";
            public const string P1_Speed_HJog_F = "DM516";

            // Row 8: Dis Step Jog-
            public const string P1_DisStep_JogMinus_X = "DM368";
            public const string P1_DisStep_JogMinus_Y = "DM398";
            public const string P1_DisStep_JogMinus_Z = "DM428";
            public const string P1_DisStep_JogMinus_RI = "DM458";
            public const string P1_DisStep_JogMinus_RO = "DM488";
            public const string P1_DisStep_JogMinus_F = "DM518";

            // Row 10: Point ABS
            public const string P1_Point_ABS_X = "DM370";
            public const string P1_Point_ABS_Y = "DM400";
            public const string P1_Point_ABS_Z = "DM430";
            public const string P1_Point_ABS_F = "DM520";

            // Row 12: Sp ABS
            public const string P1_Sp_ABS_X = "DM372";
            public const string P1_Sp_ABS_Y = "DM402";
            public const string P1_Sp_ABS_Z = "DM432";
            public const string P1_Sp_ABS_F = "DM522";

            // Production counters - Base DM2000
            public const string P1_Nber_Prd_In = "DM2000";
            public const string P1_Nber_Prd_OK = "DM2002";
            public const string P1_Nber_Prd_NG = "DM2004";
            public const string P1_Nber_Prd_Out = "DM2006";
            public const string P1_Percent_OK = "DM2008";
            public const string P1_Percent_NG = "DM2010";
            public const string P1_Time_Seconds = "DM2012";
            public const string P1_Time_Minutes = "DM2014";
            public const string P1_Time_Hours = "DM2016";
            public const string P1_Circle_Time_OK = "DM2018";
            public const string P1_Circle_Time_Now = "DM2020";

            // Position data - Tray operations DM1800
            public const string P1_Pos_Unload_Tray = "DM1800";
            public const string P1_Pos_Load_Tray = "DM1830";
            public const string P1_Pos_Align_Cam = "DM1850";
            public const string P1_Pos_UL_Socket = "DM1870";
            public const string P1_Pos_L_Socket = "DM1890";
            public const string P1_Pos_Test_LCA = "DM1910";

            // Teaching Points - Tray Input (OK)
            public const string P1_TeachPoint_TrayInput_XYStart_X = "DM2000";
            public const string P1_TeachPoint_TrayInput_XYStart_Y = "DM2002";
            public const string P1_TeachPoint_TrayInput_XEnd_X = "DM2004";
            public const string P1_TeachPoint_TrayInput_XEnd_Y = "DM2006";
            public const string P1_TeachPoint_TrayInput_YEnd_X = "DM2008";
            public const string P1_TeachPoint_TrayInput_YEnd_Y = "DM2010";
            public const string P1_TeachPoint_TrayInput_Z = "DM2070";

            // Teaching Points - Tray NG1
            public const string P1_TeachPoint_TrayNG1_XYStart_X = "DM2012";
            public const string P1_TeachPoint_TrayNG1_XYStart_Y = "DM2014";
            public const string P1_TeachPoint_TrayNG1_XEnd_X = "DM2016";
            public const string P1_TeachPoint_TrayNG1_XEnd_Y = "DM2018";
            public const string P1_TeachPoint_TrayNG1_YEnd_X = "DM2020";
            public const string P1_TeachPoint_TrayNG1_YEnd_Y = "DM2022";
            public const string P1_TeachPoint_TrayNG1_Z = "DM2068";

            // Teaching Points - Tray NG2
            public const string P1_TeachPoint_TrayNG2_XYStart_X = "DM2034";
            public const string P1_TeachPoint_TrayNG2_XYStart_Y = "DM2036";
            public const string P1_TeachPoint_TrayNG2_XEnd_X = "DM2038";
            public const string P1_TeachPoint_TrayNG2_XEnd_Y = "DM2040";
            public const string P1_TeachPoint_TrayNG2_YEnd_X = "DM2042";
            public const string P1_TeachPoint_TrayNG2_YEnd_Y = "DM2044";
            public const string P1_TeachPoint_TrayNG2_Z = "DM2068";

            // Teaching Points - Socket
            public const string P1_TeachPoint_Socket_X = "DM2052";
            public const string P1_TeachPoint_Socket_Y = "DM2054";
            public const string P1_TeachPoint_Socket_ZLoad = "DM2076";
            public const string P1_TeachPoint_Socket_ZUnload = "DM2074";
            public const string P1_TeachPoint_Socket_ZReady = "DM2060";
            public const string P1_TeachPoint_Socket_FOpened = "DM2080";
            public const string P1_TeachPoint_Socket_FClosed = "DM2078";
            public const string P1_TeachPoint_Socket_ZReadyLoad = "DM2062";
            public const string P1_TeachPoint_Socket_ZReadyUnload = "DM2064";

            // Teaching Points - Camera
            public const string P1_TeachPoint_Camera_X = "DM2092";
            public const string P1_TeachPoint_Camera_Y = "DM2094";
            public const string P1_TeachPoint_Camera_Z = "DM2072";

            #endregion

            #region Port 2 Extended Data (Base: DM0-150, DM1200-1300, DM1000-1110)

            // Axis configuration data - Columns: DM0, DM30, DM60, DM90, DM120, DM150
            // Row 0: Timeout
            public const string P2_Timeout_X = "DM0";
            public const string P2_Timeout_Y = "DM30";
            public const string P2_Timeout_Z = "DM60";
            public const string P2_Timeout_F = "DM150";

            // Row 2: Dis Step Jog+
            public const string P2_DisStep_JogPlus_X = "DM2";
            public const string P2_DisStep_JogPlus_Y = "DM32";
            public const string P2_DisStep_JogPlus_Z = "DM62";
            public const string P2_DisStep_JogPlus_RI = "DM92";
            public const string P2_DisStep_JogPlus_RO = "DM122";
            public const string P2_DisStep_JogPlus_F = "DM152";

            // Row 4: Speed LJog
            public const string P2_Speed_LJog_X = "DM4";
            public const string P2_Speed_LJog_Y = "DM34";
            public const string P2_Speed_LJog_Z = "DM64";
            public const string P2_Speed_LJog_RI = "DM94";
            public const string P2_Speed_LJog_RO = "DM124";
            public const string P2_Speed_LJog_F = "DM154";

            // Row 6: Speed HJog
            public const string P2_Speed_HJog_X = "DM6";
            public const string P2_Speed_HJog_Y = "DM36";
            public const string P2_Speed_HJog_Z = "DM66";
            public const string P2_Speed_HJog_RI = "DM96";
            public const string P2_Speed_HJog_RO = "DM126";
            public const string P2_Speed_HJog_F = "DM156";

            // Row 8: Dis Step Jog-
            public const string P2_DisStep_JogMinus_X = "DM8";
            public const string P2_DisStep_JogMinus_Y = "DM38";
            public const string P2_DisStep_JogMinus_Z = "DM68";
            public const string P2_DisStep_JogMinus_RI = "DM98";
            public const string P2_DisStep_JogMinus_RO = "DM128";
            public const string P2_DisStep_JogMinus_F = "DM158";

            // Row 10: Point ABS
            public const string P2_Point_ABS_X = "DM10";
            public const string P2_Point_ABS_Y = "DM40";
            public const string P2_Point_ABS_Z = "DM70";
            public const string P2_Point_ABS_F = "DM160";

            // Row 12: Sp ABS
            public const string P2_Sp_ABS_X = "DM12";
            public const string P2_Sp_ABS_Y = "DM42";
            public const string P2_Sp_ABS_Z = "DM72";
            public const string P2_Sp_ABS_F = "DM162";

            // Production counters - Base DM1200
            public const string P2_Nber_Prd_In = "DM1200";
            public const string P2_Nber_Prd_OK = "DM1202";
            public const string P2_Nber_Prd_NG = "DM1204";
            public const string P2_Nber_Prd_Out = "DM1206";
            public const string P2_Percent_OK = "DM1208";
            public const string P2_Percent_NG = "DM1210";
            public const string P2_Time_Seconds = "DM1212";
            public const string P2_Time_Minutes = "DM1214";
            public const string P2_Time_Hours = "DM1216";
            public const string P2_Circle_Time_OK = "DM1218";
            public const string P2_Circle_Time_Now = "DM1220";

            // Position data - Tray operations DM1000
            public const string P2_Pos_Unload_Tray = "DM1000";
            public const string P2_Pos_Load_Tray = "DM1030";
            public const string P2_Pos_Align_Cam = "DM1050";
            public const string P2_Pos_UL_Socket = "DM1070";
            public const string P2_Pos_L_Socket = "DM1090";
            public const string P2_Pos_Test_LCA = "DM1110";

            // Teaching Points - Tray Input (OK)
            public const string P2_TeachPoint_TrayInput_XYStart_X = "DM1200";
            public const string P2_TeachPoint_TrayInput_XYStart_Y = "DM1202";
            public const string P2_TeachPoint_TrayInput_XEnd_X = "DM1204";
            public const string P2_TeachPoint_TrayInput_XEnd_Y = "DM1206";
            public const string P2_TeachPoint_TrayInput_YEnd_X = "DM1208";
            public const string P2_TeachPoint_TrayInput_YEnd_Y = "DM1210";
            public const string P2_TeachPoint_TrayInput_Z = "DM1270";

            // Teaching Points - Tray NG1
            public const string P2_TeachPoint_TrayNG1_XYStart_X = "DM1212";
            public const string P2_TeachPoint_TrayNG1_XYStart_Y = "DM1214";
            public const string P2_TeachPoint_TrayNG1_XEnd_X = "DM1216";
            public const string P2_TeachPoint_TrayNG1_XEnd_Y = "DM1218";
            public const string P2_TeachPoint_TrayNG1_YEnd_X = "DM1220";
            public const string P2_TeachPoint_TrayNG1_YEnd_Y = "DM1222";
            public const string P2_TeachPoint_TrayNG1_Z = "DM1268";

            // Teaching Points - Tray NG2
            public const string P2_TeachPoint_TrayNG2_XYStart_X = "DM1234";
            public const string P2_TeachPoint_TrayNG2_XYStart_Y = "DM1236";
            public const string P2_TeachPoint_TrayNG2_XEnd_X = "DM1238";
            public const string P2_TeachPoint_TrayNG2_XEnd_Y = "DM1240";
            public const string P2_TeachPoint_TrayNG2_YEnd_X = "DM1242";
            public const string P2_TeachPoint_TrayNG2_YEnd_Y = "DM1244";
            public const string P2_TeachPoint_TrayNG2_Z = "DM1268";

            // Teaching Points - Socket
            public const string P2_TeachPoint_Socket_X = "DM1252";
            public const string P2_TeachPoint_Socket_Y = "DM1254";
            public const string P2_TeachPoint_Socket_ZLoad = "DM1276";
            public const string P2_TeachPoint_Socket_ZUnload = "DM1274";
            public const string P2_TeachPoint_Socket_ZReady = "DM1260";
            public const string P2_TeachPoint_Socket_FOpened = "DM1280";
            public const string P2_TeachPoint_Socket_FClosed = "DM1278";
            public const string P2_TeachPoint_Socket_ZReadyLoad = "DM1262";
            public const string P2_TeachPoint_Socket_ZReadyUnload = "DM1264";

            // Teaching Points - Camera
            public const string P2_TeachPoint_Camera_X = "DM1292";
            public const string P2_TeachPoint_Camera_Y = "DM1294";
            public const string P2_TeachPoint_Camera_Z = "DM1272";

            #endregion

            #region Port 3 Extended Data (Base: DM540-690, DM2400-2500, DM2200-2310)

            // Axis configuration data - Columns: DM540, DM570, DM600, DM630, DM660, DM690
            // Row 0: Timeout
            public const string P3_Timeout_X = "DM540";
            public const string P3_Timeout_Y = "DM570";
            public const string P3_Timeout_Z = "DM600";
            public const string P3_Timeout_F = "DM690";

            // Row 2: Dis Step Jog+
            public const string P3_DisStep_JogPlus_X = "DM542";
            public const string P3_DisStep_JogPlus_Y = "DM572";
            public const string P3_DisStep_JogPlus_Z = "DM602";
            public const string P3_DisStep_JogPlus_RI = "DM632";
            public const string P3_DisStep_JogPlus_RO = "DM662";
            public const string P3_DisStep_JogPlus_F = "DM692";

            // Row 4: Speed LJog
            public const string P3_Speed_LJog_X = "DM544";
            public const string P3_Speed_LJog_Y = "DM574";
            public const string P3_Speed_LJog_Z = "DM604";
            public const string P3_Speed_LJog_RI = "DM634";
            public const string P3_Speed_LJog_RO = "DM664";
            public const string P3_Speed_LJog_F = "DM694";

            // Row 6: Speed HJog
            public const string P3_Speed_HJog_X = "DM546";
            public const string P3_Speed_HJog_Y = "DM576";
            public const string P3_Speed_HJog_Z = "DM606";
            public const string P3_Speed_HJog_RI = "DM636";
            public const string P3_Speed_HJog_RO = "DM666";
            public const string P3_Speed_HJog_F = "DM696";

            // Row 8: Dis Step Jog-
            public const string P3_DisStep_JogMinus_X = "DM548";
            public const string P3_DisStep_JogMinus_Y = "DM578";
            public const string P3_DisStep_JogMinus_Z = "DM608";
            public const string P3_DisStep_JogMinus_RI = "DM638";
            public const string P3_DisStep_JogMinus_RO = "DM668";
            public const string P3_DisStep_JogMinus_F = "DM698";

            // Row 10: Point ABS
            public const string P3_Point_ABS_X = "DM550";
            public const string P3_Point_ABS_Y = "DM580";
            public const string P3_Point_ABS_Z = "DM610";
            public const string P3_Point_ABS_F = "DM700";

            // Row 12: Sp ABS
            public const string P3_Sp_ABS_X = "DM552";
            public const string P3_Sp_ABS_Y = "DM582";
            public const string P3_Sp_ABS_Z = "DM612";
            public const string P3_Sp_ABS_F = "DM702";

            // Production counters - Base DM2400
            public const string P3_Nber_Prd_In = "DM2400";
            public const string P3_Nber_Prd_OK = "DM2402";
            public const string P3_Nber_Prd_NG = "DM2404";
            public const string P3_Nber_Prd_Out = "DM2406";
            public const string P3_Percent_OK = "DM2408";
            public const string P3_Percent_NG = "DM2410";
            public const string P3_Time_Seconds = "DM2412";
            public const string P3_Time_Minutes = "DM2414";
            public const string P3_Time_Hours = "DM2416";
            public const string P3_Circle_Time_OK = "DM2418";
            public const string P3_Circle_Time_Now = "DM2420";

            // Position data - Tray operations DM2200
            public const string P3_Pos_Unload_Tray = "DM2200";
            public const string P3_Pos_Load_Tray = "DM2230";
            public const string P3_Pos_Align_Cam = "DM2250";
            public const string P3_Pos_UL_Socket = "DM2270";
            public const string P3_Pos_L_Socket = "DM2290";
            public const string P3_Pos_Test_LCA = "DM2310";

            // Teaching Points - Tray Input (OK)
            public const string P3_TeachPoint_TrayInput_XYStart_X = "DM2400";
            public const string P3_TeachPoint_TrayInput_XYStart_Y = "DM2402";
            public const string P3_TeachPoint_TrayInput_XEnd_X = "DM2404";
            public const string P3_TeachPoint_TrayInput_XEnd_Y = "DM2406";
            public const string P3_TeachPoint_TrayInput_YEnd_X = "DM2408";
            public const string P3_TeachPoint_TrayInput_YEnd_Y = "DM2410";
            public const string P3_TeachPoint_TrayInput_Z = "DM2470";

            // Teaching Points - Tray NG1
            public const string P3_TeachPoint_TrayNG1_XYStart_X = "DM2412";
            public const string P3_TeachPoint_TrayNG1_XYStart_Y = "DM2414";
            public const string P3_TeachPoint_TrayNG1_XEnd_X = "DM2416";
            public const string P3_TeachPoint_TrayNG1_XEnd_Y = "DM2418";
            public const string P3_TeachPoint_TrayNG1_YEnd_X = "DM2420";
            public const string P3_TeachPoint_TrayNG1_YEnd_Y = "DM2422";
            public const string P3_TeachPoint_TrayNG1_Z = "DM2468";

            // Teaching Points - Tray NG2
            public const string P3_TeachPoint_TrayNG2_XYStart_X = "DM2434";
            public const string P3_TeachPoint_TrayNG2_XYStart_Y = "DM2436";
            public const string P3_TeachPoint_TrayNG2_XEnd_X = "DM2438";
            public const string P3_TeachPoint_TrayNG2_XEnd_Y = "DM2440";
            public const string P3_TeachPoint_TrayNG2_YEnd_X = "DM2442";
            public const string P3_TeachPoint_TrayNG2_YEnd_Y = "DM2444";
            public const string P3_TeachPoint_TrayNG2_Z = "DM2468";

            // Teaching Points - Socket
            public const string P3_TeachPoint_Socket_X = "DM2452";
            public const string P3_TeachPoint_Socket_Y = "DM2454";
            public const string P3_TeachPoint_Socket_ZLoad = "DM2476";
            public const string P3_TeachPoint_Socket_ZUnload = "DM2474";
            public const string P3_TeachPoint_Socket_ZReady = "DM2460";
            public const string P3_TeachPoint_Socket_FOpened = "DM2480";
            public const string P3_TeachPoint_Socket_FClosed = "DM2478";
            public const string P3_TeachPoint_Socket_ZReadyLoad = "DM2462";
            public const string P3_TeachPoint_Socket_ZReadyUnload = "DM2464";

            // Teaching Points - Camera
            public const string P3_TeachPoint_Camera_X = "DM2492";
            public const string P3_TeachPoint_Camera_Y = "DM2494";
            public const string P3_TeachPoint_Camera_Z = "DM2472";

            #endregion

            #region Port 4 Extended Data (Base: DM180-330, DM1600-1700, DM1400-1510)

            // Axis configuration data - Columns: DM180, DM210, DM240, DM270, DM300, DM330
            // Row 0: Timeout
            public const string P4_Timeout_X = "DM180";
            public const string P4_Timeout_Y = "DM210";
            public const string P4_Timeout_Z = "DM240";
            public const string P4_Timeout_F = "DM330";

            // Row 2: Dis Step Jog+
            public const string P4_DisStep_JogPlus_X = "DM182";
            public const string P4_DisStep_JogPlus_Y = "DM212";
            public const string P4_DisStep_JogPlus_Z = "DM242";
            public const string P4_DisStep_JogPlus_RI = "DM272";
            public const string P4_DisStep_JogPlus_RO = "DM302";
            public const string P4_DisStep_JogPlus_F = "DM332";

            // Row 4: Speed LJog
            public const string P4_Speed_LJog_X = "DM184";
            public const string P4_Speed_LJog_Y = "DM214";
            public const string P4_Speed_LJog_Z = "DM244";
            public const string P4_Speed_LJog_RI = "DM274";
            public const string P4_Speed_LJog_RO = "DM304";
            public const string P4_Speed_LJog_F = "DM334";

            // Row 6: Speed HJog
            public const string P4_Speed_HJog_X = "DM186";
            public const string P4_Speed_HJog_Y = "DM216";
            public const string P4_Speed_HJog_Z = "DM246";
            public const string P4_Speed_HJog_RI = "DM276";
            public const string P4_Speed_HJog_RO = "DM306";
            public const string P4_Speed_HJog_F = "DM336";

            // Row 8: Dis Step Jog-
            public const string P4_DisStep_JogMinus_X = "DM188";
            public const string P4_DisStep_JogMinus_Y = "DM218";
            public const string P4_DisStep_JogMinus_Z = "DM248";
            public const string P4_DisStep_JogMinus_RI = "DM278";
            public const string P4_DisStep_JogMinus_RO = "DM308";
            public const string P4_DisStep_JogMinus_F = "DM338";

            // Row 10: Point ABS
            public const string P4_Point_ABS_X = "DM190";
            public const string P4_Point_ABS_Y = "DM220";
            public const string P4_Point_ABS_Z = "DM250";
            public const string P4_Point_ABS_F = "DM340";

            // Row 12: Sp ABS
            public const string P4_Sp_ABS_X = "DM192";
            public const string P4_Sp_ABS_Y = "DM222";
            public const string P4_Sp_ABS_Z = "DM252";
            public const string P4_Sp_ABS_F = "DM342";

            // Production counters - Base DM1600
            public const string P4_Nber_Prd_In = "DM1600";
            public const string P4_Nber_Prd_OK = "DM1602";
            public const string P4_Nber_Prd_NG = "DM1604";
            public const string P4_Nber_Prd_Out = "DM1606";
            public const string P4_Percent_OK = "DM1608";
            public const string P4_Percent_NG = "DM1610";
            public const string P4_Time_Seconds = "DM1612";
            public const string P4_Time_Minutes = "DM1614";
            public const string P4_Time_Hours = "DM1616";
            public const string P4_Circle_Time_OK = "DM1618";
            public const string P4_Circle_Time_Now = "DM1620";

            // Position data - Tray operations DM1400
            public const string P4_Pos_Unload_Tray = "DM1400";
            public const string P4_Pos_Load_Tray = "DM1430";
            public const string P4_Pos_Align_Cam = "DM1450";
            public const string P4_Pos_UL_Socket = "DM1470";
            public const string P4_Pos_L_Socket = "DM1490";
            public const string P4_Pos_Test_LCA = "DM1510";

            // Teaching Points - Tray Input (OK)
            public const string P4_TeachPoint_TrayInput_XYStart_X = "DM1600";
            public const string P4_TeachPoint_TrayInput_XYStart_Y = "DM1602";
            public const string P4_TeachPoint_TrayInput_XEnd_X = "DM1604";
            public const string P4_TeachPoint_TrayInput_XEnd_Y = "DM1606";
            public const string P4_TeachPoint_TrayInput_YEnd_X = "DM1608";
            public const string P4_TeachPoint_TrayInput_YEnd_Y = "DM1610";
            public const string P4_TeachPoint_TrayInput_Z = "DM1670";

            // Teaching Points - Tray NG1
            public const string P4_TeachPoint_TrayNG1_XYStart_X = "DM1612";
            public const string P4_TeachPoint_TrayNG1_XYStart_Y = "DM1614";
            public const string P4_TeachPoint_TrayNG1_XEnd_X = "DM1616";
            public const string P4_TeachPoint_TrayNG1_XEnd_Y = "DM1618";
            public const string P4_TeachPoint_TrayNG1_YEnd_X = "DM1620";
            public const string P4_TeachPoint_TrayNG1_YEnd_Y = "DM1622";
            public const string P4_TeachPoint_TrayNG1_Z = "DM1668";

            // Teaching Points - Tray NG2
            public const string P4_TeachPoint_TrayNG2_XYStart_X = "DM1634";
            public const string P4_TeachPoint_TrayNG2_XYStart_Y = "DM1636";
            public const string P4_TeachPoint_TrayNG2_XEnd_X = "DM1638";
            public const string P4_TeachPoint_TrayNG2_XEnd_Y = "DM1640";
            public const string P4_TeachPoint_TrayNG2_YEnd_X = "DM1642";
            public const string P4_TeachPoint_TrayNG2_YEnd_Y = "DM1644";
            public const string P4_TeachPoint_TrayNG2_Z = "DM1668";

            // Teaching Points - Socket
            public const string P4_TeachPoint_Socket_X = "DM1652";
            public const string P4_TeachPoint_Socket_Y = "DM1654";
            public const string P4_TeachPoint_Socket_ZLoad = "DM1676";
            public const string P4_TeachPoint_Socket_ZUnload = "DM1674";
            public const string P4_TeachPoint_Socket_ZReady = "DM1660";
            public const string P4_TeachPoint_Socket_FOpened = "DM1680";
            public const string P4_TeachPoint_Socket_FClosed = "DM1678";
            public const string P4_TeachPoint_Socket_ZReadyLoad = "DM1662";
            public const string P4_TeachPoint_Socket_ZReadyUnload = "DM1664";

            // Teaching Points - Camera
            public const string P4_TeachPoint_Camera_X = "DM1692";
            public const string P4_TeachPoint_Camera_Y = "DM1694";
            public const string P4_TeachPoint_Camera_Z = "DM1672";

            #endregion

            #region Shared NG Data (All Ports)

            // NG (Not Good) data - Shared across all ports
            public const string Data_NG1 = "DM900";
            public const string Data_NG2 = "DM920";
            public const string Data_NG3 = "DM940";
            public const string Data_NG4 = "DM960";

            #endregion

        }

    }
}
