//------------------------------------------------------------------------------
// <auto-generated>
//     File này được tạo tự động từ PLCConfig.json
//     Thời gian: 2025-10-29 (Initial version)
//     KHÔNG CHỈNH SỬA TRỰC TIẾP FILE NÀY!
//
//     Để regenerate file này, chạy:
//     PLCConfigManager manager = new PLCConfigManager();
//     manager.LoadConfig("PLCConfig.json");
//     manager.GenerateAddressesFile("PLCAddresses.Generated.cs");
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom;

namespace PLCKeygen
{
    /// <summary>
    /// Địa chỉ PLC được generate tự động từ PLCConfig.json
    /// PLC: Keyence_PLC_Main (192.168.1.100:8501)
    /// </summary>
    public static class PLCAddresses
    {
        public const string PLCName = "Keyence_PLC_Main";
        public const string IPAddress = "192.168.1.100";
        public const int Port = 8501;

        /// <summary>
        /// Địa chỉ Input (đầu vào)
        /// </summary>
        public static class Input
        {
            #region Port 1 Jog
            public const string P1_Step_Jog_Mode =  "MR02002";
            public const string P1_XJog_Plus =  "MR43701";
            public const string P1_XJog_Minus = "MR43702";
            public const string P1_XHome =      "MR43700";
            public const string P1_XReset =     "MR43705";
            public const string P1_XGo_ABS =    "MR43703";
            public const string P1_XGo_INC =    "MR43704";
            public const string P1_YJog_Plus =  "MR44001";
            public const string P1_YJog_Minus = "MR44002";
            public const string P1_YHome =      "MR44000";
            public const string P1_YReset =     "MR44005";
            public const string P1_YGo_ABS =    "MR44003";
            public const string P1_YGo_INC =    "MR44004";
            public const string P1_ZJog_Plus =  "MR44301";
            public const string P1_ZJog_Minus = "MR44302";
            public const string P1_ZHome =      "MR44300";
            public const string P1_ZReset =     "MR44305";
            public const string P1_ZGo_ABS =    "MR44303";
            public const string P1_ZGo_INC =    "MR44304";
            public const string P1_RIJog_Plus = "MR44601";
            public const string P1_RIJog_Minus ="MR44602";
            public const string P1_RIHome =     "MR44600";
            public const string P1_RIReset =    "MR44605";
            public const string P1_RIGo_ABS =   "MR44603";
            public const string P1_RIGo_INC =   "MR44604";
            public const string P1_ROJog_Plus = "MR44901";
            public const string P1_ROJog_Minus ="MR44902";
            public const string P1_ROHome =     "MR44900";
            public const string P1_ROReset =    "MR44905";
            public const string P1_ROGo_ABS =   "MR44903";
            public const string P1_ROGo_INC =   "MR44904";
            public const string P1_FJog_Plus =  "MR45201";
            public const string P1_FJog_Minus = "MR45202";
            public const string P1_FHome =      "MR45200";
            public const string P1_FReset =     "MR45205";
            public const string P1_FGo_ABS =    "MR45203";
            public const string P1_FGo_INC =    "MR45204";
            #endregion

            #region Port 2 Jog
            public const string P2_Step_Jog_Mode = "MR00002";
            public const string P2_XJog_Plus =  "MR40101";
            public const string P2_XJog_Minus = "MR40102";
            public const string P2_XHome =      "MR40100";
            public const string P2_XReset =     "MR40105";
            public const string P2_XGo_ABS =    "MR40103";
            public const string P2_XGo_INC =    "MR40104";
            public const string P2_YJog_Plus =  "MR40401";
            public const string P2_YJog_Minus = "MR40402";
            public const string P2_YHome =      "MR40400";
            public const string P2_YReset =     "MR40405";
            public const string P2_YGo_ABS =    "MR40403";
            public const string P2_YGo_INC =    "MR40404";
            public const string P2_ZJog_Plus =  "MR40701";
            public const string P2_ZJog_Minus = "MR40702";
            public const string P2_ZHome =      "MR40700";
            public const string P2_ZReset =     "MR40705";
            public const string P2_ZGo_ABS =    "MR40703";
            public const string P2_ZGo_INC =    "MR40704";
            public const string P2_RIJog_Plus = "MR41001";
            public const string P2_RIJog_Minus ="MR41002";
            public const string P2_RIHome =     "MR41000";
            public const string P2_RIReset =    "MR41005";
            public const string P2_RIGo_ABS =   "MR41003";
            public const string P2_RIGo_INC =   "MR41004";
            public const string P2_ROJog_Plus = "MR41301";
            public const string P2_ROJog_Minus ="MR41302";
            public const string P2_ROHome =     "MR41300";
            public const string P2_ROReset =    "MR41305";
            public const string P2_ROGo_ABS =   "MR41303";
            public const string P2_ROGo_INC =   "MR41304";
            public const string P2_FJog_Plus =  "MR41601";
            public const string P2_FJog_Minus = "MR41602";
            public const string P2_FHome =      "MR41600";
            public const string P2_FReset =     "MR41605";
            public const string P2_FGo_ABS =    "MR41603";
            public const string P2_FGo_INC =    "MR41604";
            #endregion

            #region Port 3 Jog
            public const string P3_Step_Jog_Mode = "MR03002";
            public const string P3_XJog_Plus =  "MR45501";
            public const string P3_XJog_Minus = "MR45502";
            public const string P3_XHome =      "MR45500";
            public const string P3_XReset =     "MR45505";
            public const string P3_XGo_ABS =    "MR45503";
            public const string P3_XGo_INC =    "MR45504";
            public const string P3_YJog_Plus =  "MR45801";
            public const string P3_YJog_Minus = "MR45802";
            public const string P3_YHome =      "MR45800";
            public const string P3_YReset =     "MR45805";
            public const string P3_YGo_ABS =    "MR45803";
            public const string P3_YGo_INC =    "MR45804";
            public const string P3_ZJog_Plus =  "MR46101";
            public const string P3_ZJog_Minus = "MR46102";
            public const string P3_ZHome =      "MR46100";
            public const string P3_ZReset =     "MR46105";
            public const string P3_ZGo_ABS =    "MR46103";
            public const string P3_ZGo_INC =    "MR46104";
            public const string P3_RIJog_Plus = "MR46401";
            public const string P3_RIJog_Minus ="MR46402";
            public const string P3_RIHome =     "MR46400";
            public const string P3_RIReset =    "MR46405";
            public const string P3_RIGo_ABS =   "MR46403";
            public const string P3_RIGo_INC =   "MR46404";
            public const string P3_ROJog_Plus = "MR46701";
            public const string P3_ROJog_Minus ="MR46702";
            public const string P3_ROHome =     "MR46700";
            public const string P3_ROReset =    "MR46705";
            public const string P3_ROGo_ABS =   "MR46703";
            public const string P3_ROGo_INC =   "MR46704";
            public const string P3_FJog_Plus =  "MR47001";
            public const string P3_FJog_Minus = "MR47002";
            public const string P3_FHome =      "MR47000";
            public const string P3_FReset =     "MR47005";
            public const string P3_FGo_ABS =    "MR47003";
            public const string P3_FGo_INC =    "MR47004";
            #endregion

            #region Port 4 Jog
            public const string P4_Step_Jog_Mode = "MR01002";
            public const string P4_XJog_Plus =  "MR41901";
            public const string P4_XJog_Minus = "MR41902";
            public const string P4_XHome =      "MR41900";
            public const string P4_XReset =     "MR41905";
            public const string P4_XGo_ABS =    "MR41903";
            public const string P4_XGo_INC =    "MR41904";
            public const string P4_YJog_Plus =  "MR42201";
            public const string P4_YJog_Minus = "MR42202";
            public const string P4_YHome =      "MR42200";
            public const string P4_YReset =     "MR42205";
            public const string P4_YGo_ABS =    "MR42203";
            public const string P4_YGo_INC =    "MR42204";
            public const string P4_ZJog_Plus =  "MR42501";
            public const string P4_ZJog_Minus = "MR42502";
            public const string P4_ZHome =      "MR42500";
            public const string P4_ZReset =     "MR42505";
            public const string P4_ZGo_ABS =    "MR42503";
            public const string P4_ZGo_INC =    "MR42504";
            public const string P4_RIJog_Plus = "MR42801";
            public const string P4_RIJog_Minus ="MR42802";
            public const string P4_RIHome =     "MR42800";
            public const string P4_RIReset =    "MR42805";
            public const string P4_RIGo_ABS =   "MR42803";
            public const string P4_RIGo_INC =   "MR42804";
            public const string P4_ROJog_Plus = "MR43101";
            public const string P4_ROJog_Minus ="MR43102";
            public const string P4_ROHome =     "MR43100";
            public const string P4_ROReset =    "MR43105";
            public const string P4_ROGo_ABS =   "MR43103";
            public const string P4_ROGo_INC =   "MR43104";
            public const string P4_FJog_Plus =  "MR43401";
            public const string P4_FJog_Minus = "MR43402";
            public const string P4_FHome =      "MR43400";
            public const string P4_FReset =     "MR43405";
            public const string P4_FGo_ABS =    "MR43403";
            public const string P4_FGo_INC =    "MR43404";
            #endregion

            #region Port 1 I/O Sensors (MR21, MR22)

            // ===== MR21 Register =====
            /// <summary>Sensor: Input - Ss VIn1</summary>
            public const string P1_Ss_VIn1 = "MR2100";

            /// <summary>Sensor: Output - Ss VOt1</summary>
            public const string P1_Ss_VOt1 = "MR2101";

            /// <summary>Sensor: Camera Port 1 Vacuum - Ss VCa21 Port1</summary>
            public const string P1_Ss_VCa21_Port1 = "MR2102";

            /// <summary>Sensor: Camera Port 2 Vacuum - Ss VCa21 Port2</summary>
            public const string P1_Ss_VCa21_Port2 = "MR2103";

            /// <summary>Sensor: Fixture Open - Ss Fix1 Open</summary>
            public const string P1_Ss_Fix1_Open = "MR2104";

            /// <summary>Sensor: Fixture Close - Ss Fix1 Close</summary>
            public const string P1_Ss_Fix1_Close = "MR2105";

            /// <summary>Status: Tower Light Start - Stt lca Start1</summary>
            public const string P1_Stt_lca_Start1 = "MR2106";

            /// <summary>Status: Tower Light Stop - Stt lca Stop1</summary>
            public const string P1_Stt_lca_Stop1 = "MR2107";

            /// <summary>Status: Tower Light Green - Stt lca Gre1</summary>
            public const string P1_Stt_lca_Gre1 = "MR2108";

            /// <summary>Status: Tower Light Yellow - Stt lca Yel1</summary>
            public const string P1_Stt_lca_Yel1 = "MR2109";

            /// <summary>Status: Tower Light Red - Stt lca Red1</summary>
            public const string P1_Stt_lca_Red1 = "MR2110";

            /// <summary>Sensor: Door 1 - Ss Door1</summary>
            public const string P1_Ss_Door1 = "MR2111";

            /// <summary>Sensor: Jig OK - Ss Jig OK</summary>
            public const string P1_Ss_Jig_OK = "MR2112";

            /// <summary>Sensor: Tray OK - Ss Tray OK</summary>
            public const string P1_Ss_Tray_OK = "MR2113";

            /// <summary>Sensor: Jig NG - Ss Jig NG</summary>
            public const string P1_Ss_Jig_NG = "MR2114";

            /// <summary>Sensor: Tray NG - Ss Tray NG</summary>
            public const string P1_Ss_Tray_NG = "MR2115";

            // ===== MR22 Register =====
            /// <summary>Sensor: Jig NG4 - Ss Jig NG4</summary>
            public const string P1_Ss_Jig_NG4 = "MR2200";

            /// <summary>Sensor: Tray NG4 - Ss Tray NG4</summary>
            public const string P1_Ss_Tray_NG4 = "MR2201";

            /// <summary>Switch: Emergency Stop 1 - SW EMS1</summary>
            public const string P1_SW_EMS1 = "MR2202";

            /// <summary>Switch: Start 1 - SW Start1</summary>
            public const string P1_SW_Start1 = "MR2203";

            /// <summary>Switch: Stop 1 - SW Stop1</summary>
            public const string P1_SW_Stop1 = "MR2204";

            /// <summary>Switch: Reset 1 - SW Reset1</summary>
            public const string P1_SW_Reset1 = "MR2205";

            /// <summary>Sensor: Air Positive 1 - Ss Air+1</summary>
            public const string P1_Ss_AirPlus1 = "MR2206";

            /// <summary>Sensor: Air Negative 1 - Ss Air-1</summary>
            public const string P1_Ss_AirMinus1 = "MR2207";

            /// <summary>Sensor: Vision Seek 1 - Ss VSk1</summary>
            public const string P1_Ss_VSk1 = "MR2208";

            /// <summary>Switch: Initialize 1 - SW Init1</summary>
            public const string P1_SW_Init1 = "MR2209";

            #endregion

            #region Port 2 I/O Sensors (MR1, MR2)

            // ===== MR1 Register =====
            /// <summary>Sensor: Input - Ss VIn2</summary>
            public const string P2_Ss_VIn2 = "MR100";

            /// <summary>Sensor: Output - Ss VOt2</summary>
            public const string P2_Ss_VOt2 = "MR101";

            /// <summary>Sensor: Camera Port 2 Vacuum - Ss VCa12 Port2</summary>
            public const string P2_Ss_VCa12_Port2 = "MR102";

            /// <summary>Sensor: Camera Port 1 Vacuum - Ss VCa12 Port1</summary>
            public const string P2_Ss_VCa12_Port1 = "MR103";

            /// <summary>Sensor: Fixture 2 Open - Ss Fix2 Open</summary>
            public const string P2_Ss_Fix2_Open = "MR104";

            /// <summary>Sensor: Fixture 2 Close - Ss Fix2 Close</summary>
            public const string P2_Ss_Fix2_Close = "MR105";

            /// <summary>Status: Tower Light Start 2 / StatusTester - Stt lca Start2</summary>
            public const string P2_Stt_lca_Start2_StatusTester = "MR106";

            /// <summary>Status: Tower Light Stop 2 / StatusTester - Stt lca Stop2</summary>
            public const string P2_Stt_lca_Stop2_StatusTester = "MR107";

            /// <summary>Status: Tower Light Green 2 - Stt lca Gre2</summary>
            public const string P2_Stt_lca_Gre2 = "MR108";

            /// <summary>Status: Tower Light Yellow 2 - Stt lca Yel2</summary>
            public const string P2_Stt_lca_Yel2 = "MR109";

            /// <summary>Status: Tower Light Red 2 - Stt lca Red2</summary>
            public const string P2_Stt_lca_Red2 = "MR110";

            /// <summary>Sensor: Door 2 - Ss Door2</summary>
            public const string P2_Ss_Door2 = "MR111";

            /// <summary>Sensor: Jig OK - Ss Jig OK</summary>
            public const string P2_Ss_Jig_OK = "MR112";

            /// <summary>Sensor: Tray OK - Ss Tray OK</summary>
            public const string P2_Ss_Tray_OK = "MR113";

            /// <summary>Sensor: Jig NG - Ss Jig NG</summary>
            public const string P2_Ss_Jig_NG = "MR114";

            /// <summary>Sensor: Tray NG - Ss Tray NG</summary>
            public const string P2_Ss_Tray_NG = "MR115";

            // ===== MR2 Register =====
            /// <summary>Sensor: Jig NG4 - Ss Jig NG4</summary>
            public const string P2_Ss_Jig_NG4 = "MR200";

            /// <summary>Sensor: Tray NG4 - Ss Tray NG4</summary>
            public const string P2_Ss_Tray_NG4 = "MR201";

            /// <summary>Switch: Emergency Stop 2 - SW EMS2</summary>
            public const string P2_SW_EMS2 = "MR202";

            /// <summary>Switch: Start 2 - SW Start2</summary>
            public const string P2_SW_Start2 = "MR203";

            /// <summary>Switch: Stop 2 - SW Stop2</summary>
            public const string P2_SW_Stop2 = "MR204";

            /// <summary>Switch: Reset 2 - SW Reset2</summary>
            public const string P2_SW_Reset2 = "MR205";

            /// <summary>Sensor: Air Positive 2 - Ss Air+2</summary>
            public const string P2_Ss_AirPlus2 = "MR206";

            /// <summary>Sensor: Air Negative 2 - Ss Air-2</summary>
            public const string P2_Ss_AirMinus2 = "MR207";

            /// <summary>Sensor: Vision Seek 2 - Ss VSk2</summary>
            public const string P2_Ss_VSk2 = "MR208";

            /// <summary>Switch: Initialize 2 - SW Init2</summary>
            public const string P2_SW_Init2 = "MR209";

            #endregion

            #region Port 3 I/O Sensors (MR31, MR32)

            // ===== MR31 Register =====
            /// <summary>Sensor: Input - Ss VIn3</summary>
            public const string P3_Ss_VIn3 = "MR3100";

            /// <summary>Sensor: Output - Ss VOt3</summary>
            public const string P3_Ss_VOt3 = "MR3101";

            /// <summary>Sensor: Camera Port 3 Vacuum - Ss VCa34 Port3</summary>
            public const string P3_Ss_VCa34_Port3 = "MR3102";

            /// <summary>Sensor: Camera Port 4 Vacuum - Ss VCa34 Port4</summary>
            public const string P3_Ss_VCa34_Port4 = "MR3103";

            /// <summary>Sensor: Fixture 3 Open - Ss Fix3 Open</summary>
            public const string P3_Ss_Fix3_Open = "MR3104";

            /// <summary>Sensor: Fixture 3 Close - Ss Fix3 Close</summary>
            public const string P3_Ss_Fix3_Close = "MR3105";

            /// <summary>Status: Tower Light Start 3 - Stt lca Start3</summary>
            public const string P3_Stt_lca_Start3 = "MR3106";

            /// <summary>Status: Tower Light Stop 3 - Stt lca Stop3</summary>
            public const string P3_Stt_lca_Stop3 = "MR3107";

            /// <summary>Status: Tower Light Green 3 - Stt lca Gre3</summary>
            public const string P3_Stt_lca_Gre3 = "MR3108";

            /// <summary>Status: Tower Light Yellow 3 - Stt lca Yel3</summary>
            public const string P3_Stt_lca_Yel3 = "MR3109";

            /// <summary>Status: Tower Light Red 3 - Stt lca Red3</summary>
            public const string P3_Stt_lca_Red3 = "MR3110";

            /// <summary>Sensor: Door 3 - Ss Door3</summary>
            public const string P3_Ss_Door3 = "MR3111";

            /// <summary>Sensor: Jig OK - Ss Jig OK</summary>
            public const string P3_Ss_Jig_OK = "MR3112";

            /// <summary>Sensor: Tray OK - Ss Tray OK</summary>
            public const string P3_Ss_Tray_OK = "MR3113";

            /// <summary>Sensor: Jig NG - Ss Jig NG</summary>
            public const string P3_Ss_Jig_NG = "MR3114";

            /// <summary>Sensor: Tray NG - Ss Tray NG</summary>
            public const string P3_Ss_Tray_NG = "MR3115";

            // ===== MR32 Register =====
            /// <summary>Sensor: Jig NG4 - Ss Jig NG4</summary>
            public const string P3_Ss_Jig_NG4 = "MR3200";

            /// <summary>Sensor: Tray NG4 - Ss Tray NG4</summary>
            public const string P3_Ss_Tray_NG4 = "MR3201";

            /// <summary>Switch: Emergency Stop 3 - SW EMS3</summary>
            public const string P3_SW_EMS3 = "MR3202";

            /// <summary>Switch: Start 3 - SW Start3</summary>
            public const string P3_SW_Start3 = "MR3203";

            /// <summary>Switch: Stop 3 - SW Stop3</summary>
            public const string P3_SW_Stop3 = "MR3204";

            /// <summary>Switch: Reset 3 - SW Reset3</summary>
            public const string P3_SW_Reset3 = "MR3205";

            /// <summary>Sensor: Air Positive 3 - Ss Air+3</summary>
            public const string P3_Ss_AirPlus3 = "MR3206";

            /// <summary>Sensor: Air Negative 3 - Ss Air-3</summary>
            public const string P3_Ss_AirMinus3 = "MR3207";

            /// <summary>Sensor: Vision Seek 3 - Ss VSk3</summary>
            public const string P3_Ss_VSk3 = "MR3208";

            /// <summary>Switch: Initialize 3 - SW Init3</summary>
            public const string P3_SW_Init3 = "MR3209";

            #endregion

            #region Port 4 I/O Sensors (MR11, MR12)

            // ===== MR11 Register =====
            /// <summary>Sensor: Input - Ss VIn4</summary>
            public const string P4_Ss_VIn4 = "MR1100";

            /// <summary>Sensor: Output - Ss VOt24</summary>
            public const string P4_Ss_VOt24 = "MR1101";

            /// <summary>Sensor: Camera Port 4 Vacuum - Ss VCa34 Port4</summary>
            public const string P4_Ss_VCa34_Port4 = "MR1102";

            /// <summary>Sensor: Camera Port 3 Vacuum - Ss VCa34 Port3</summary>
            public const string P4_Ss_VCa34_Port3 = "MR1103";

            /// <summary>Sensor: Fixture 4 Open - Ss Fix4 Open</summary>
            public const string P4_Ss_Fix4_Open = "MR1104";

            /// <summary>Sensor: Fixture 4 Close - Ss Fix4 Close</summary>
            public const string P4_Ss_Fix4_Close = "MR1105";

            /// <summary>Status: Tower Light Start 4 - Stt lca Start4</summary>
            public const string P4_Stt_lca_Start4 = "MR1106";

            /// <summary>Status: Tower Light Stop 4 - Stt lca Stop4</summary>
            public const string P4_Stt_lca_Stop4 = "MR1107";

            /// <summary>Status: Tower Light Green 4 - Stt lca Gre4</summary>
            public const string P4_Stt_lca_Gre4 = "MR1108";

            /// <summary>Status: Tower Light Yellow 4 - Stt lca Yel4</summary>
            public const string P4_Stt_lca_Yel4 = "MR1109";

            /// <summary>Status: Tower Light Red 4 - Stt lca Red4</summary>
            public const string P4_Stt_lca_Red4 = "MR1110";

            /// <summary>Sensor: Door 4 - Ss Door4</summary>
            public const string P4_Ss_Door4 = "MR1111";

            /// <summary>Sensor: Jig OK - Ss Jig OK</summary>
            public const string P4_Ss_Jig_OK = "MR1112";

            /// <summary>Sensor: Tray OK - Ss Tray OK</summary>
            public const string P4_Ss_Tray_OK = "MR1113";

            /// <summary>Sensor: Jig NG - Ss Jig NG</summary>
            public const string P4_Ss_Jig_NG = "MR1114";

            /// <summary>Sensor: Tray NG - Ss Tray NG</summary>
            public const string P4_Ss_Tray_NG = "MR1115";

            // ===== MR12 Register =====
            /// <summary>Sensor: Jig NG4 - Ss Jig NG4</summary>
            public const string P4_Ss_Jig_NG4 = "MR1200";

            /// <summary>Sensor: Tray NG4 - Ss Tray NG4</summary>
            public const string P4_Ss_Tray_NG4 = "MR1201";

            /// <summary>Switch: Emergency Stop 4 - SW EMS4</summary>
            public const string P4_SW_EMS4 = "MR1202";

            /// <summary>Switch: Start 4 - SW Start4</summary>
            public const string P4_SW_Start4 = "MR1203";

            /// <summary>Switch: Stop 4 - SW Stop4</summary>
            public const string P4_SW_Stop4 = "MR1204";

            /// <summary>Switch: Reset 4 - SW Reset4</summary>
            public const string P4_SW_Reset4 = "MR1205";

            /// <summary>Sensor: Air Positive 4 - Ss Air+4</summary>
            public const string P4_Ss_AirPlus4 = "MR1206";

            /// <summary>Sensor: Air Negative 4 - Ss Air-4</summary>
            public const string P4_Ss_AirMinus4 = "MR1207";

            /// <summary>Sensor: Vision Seek 4 - Ss VSk4</summary>
            public const string P4_Ss_VSk4 = "MR1208";

            /// <summary>Switch: Initialize 4 - SW Init4</summary>
            public const string P4_SW_Init4 = "MR1209";

            #endregion
        }

        /// <summary>
        /// Địa chỉ Output (đầu ra)
        /// </summary>
        public static class Output
        {
            #region Camera Cylinders
            /// <summary>Xi lanh camera Port 1-2</summary>
            public const string P12_Cam_cylinder = "MR5002";

            /// <summary>Xi lanh camera Port 3-4</summary>
            public const string P34_Cam_cylinder = "MR6002";
            #endregion

            #region Port 1 Outputs - Tower Lights
            /// <summary>Đèn tháp xanh Port 1 - Tower Light Green</summary>
            public const string P1_Tower_Green = "MR2108";

            /// <summary>Đèn tháp vàng Port 1 - Tower Light Yellow</summary>
            public const string P1_Tower_Yellow = "MR2109";

            /// <summary>Đèn tháp đỏ Port 1 - Tower Light Red</summary>
            public const string P1_Tower_Red = "MR2110";

            /// <summary>Đèn tháp Start Port 1 - Tower Light Start</summary>
            public const string P1_Tower_Start = "MR2106";

            /// <summary>Đèn tháp Stop Port 1 - Tower Light Stop</summary>
            public const string P1_Tower_Stop = "MR2107";
            #endregion

            #region Port 2 Outputs - Tower Lights
            /// <summary>Đèn tháp xanh Port 2 - Tower Light Green</summary>
            public const string P2_Tower_Green = "MR108";

            /// <summary>Đèn tháp vàng Port 2 - Tower Light Yellow</summary>
            public const string P2_Tower_Yellow = "MR109";

            /// <summary>Đèn tháp đỏ Port 2 - Tower Light Red</summary>
            public const string P2_Tower_Red = "MR110";

            /// <summary>Đèn tháp Start Port 2 - Tower Light Start</summary>
            public const string P2_Tower_Start = "MR106";

            /// <summary>Đèn tháp Stop Port 2 - Tower Light Stop</summary>
            public const string P2_Tower_Stop = "MR107";
            #endregion

            #region Port 3 Outputs - Tower Lights
            /// <summary>Đèn tháp xanh Port 3 - Tower Light Green</summary>
            public const string P3_Tower_Green = "MR3108";

            /// <summary>Đèn tháp vàng Port 3 - Tower Light Yellow</summary>
            public const string P3_Tower_Yellow = "MR3109";

            /// <summary>Đèn tháp đỏ Port 3 - Tower Light Red</summary>
            public const string P3_Tower_Red = "MR3110";

            /// <summary>Đèn tháp Start Port 3 - Tower Light Start</summary>
            public const string P3_Tower_Start = "MR3106";

            /// <summary>Đèn tháp Stop Port 3 - Tower Light Stop</summary>
            public const string P3_Tower_Stop = "MR3107";
            #endregion

            #region Port 4 Outputs (MR60)

            /// <summary>Request: Input Valve - Rq Vin4</summary>
            public const string P4_Rq_Vin4 = "MR6000";

            /// <summary>Request: Output Valve - Rq Vout4</summary>
            public const string P4_Rq_Vout4 = "MR6001";

            /// <summary>Request: Camera Vacuum 34 - Rq VCam34 (same as P34_Cam_cylinder)</summary>
            public const string P4_Rq_VCam34 = "MR6002";

            /// <summary>Request: Fixture Valve - Rq VFix4</summary>
            public const string P4_Rq_VFix4 = "MR6003";

            /// <summary>Request: Tower Light Init 4 - Rq lca Init4</summary>
            public const string P4_Rq_lca_Init4 = "MR6004";

            /// <summary>Request: Tower Light Start Tester 4 - Rq lca StartT4</summary>
            public const string P4_Rq_lca_StartT4 = "MR6005";

            /// <summary>Request: Tower Light Stop Tester 4 - Rq lca StopT4</summary>
            public const string P4_Rq_lca_StopT4 = "MR6006";

            /// <summary>Request: Tower Light Reset 4 - Rq lca Res4</summary>
            public const string P4_Rq_lca_Res4 = "MR6007";

            /// <summary>Đèn tháp xanh Port 4 - Tower Light Green - Rq L Gre4</summary>
            public const string P4_Tower_Green = "MR6008";

            /// <summary>Đèn tháp đỏ Port 4 - Tower Light Red - Rq L Red4</summary>
            public const string P4_Tower_Red = "MR6009";

            /// <summary>Đèn tháp vàng Port 4 - Tower Light Yellow - Rq L Yel4</summary>
            public const string P4_Tower_Yellow = "MR6010";

            /// <summary>Đèn tháp Start Port 4 - Tower Light Start - Rq L Start4</summary>
            public const string P4_Tower_Start = "MR6011";

            /// <summary>Đèn tháp Stop Port 4 - Tower Light Stop - Rq L Stop4</summary>
            public const string P4_Tower_Stop = "MR6012";

            /// <summary>Request: Vision Check Seek 4 - Rq VChck Sk4</summary>
            public const string P4_Rq_VChck_Sk4 = "MR6013";

            #endregion

            #region Helper Methods
            /// <summary>
            /// Lấy địa chỉ đèn tháp theo port và màu
            /// Get tower light address by port and color
            /// </summary>
            /// <param name="port">Port number (1-4)</param>
            /// <param name="color">Color: GREEN, YELLOW, RED, START, STOP</param>
            /// <returns>PLC address string</returns>
            public static string GetTowerLight(int port, string color)
            {
                color = color.ToUpper();

                switch (port)
                {
                    case 1:
                        if (color == "GREEN") return P1_Tower_Green;
                        if (color == "YELLOW") return P1_Tower_Yellow;
                        if (color == "RED") return P1_Tower_Red;
                        if (color == "START") return P1_Tower_Start;
                        if (color == "STOP") return P1_Tower_Stop;
                        break;
                    case 2:
                        if (color == "GREEN") return P2_Tower_Green;
                        if (color == "YELLOW") return P2_Tower_Yellow;
                        if (color == "RED") return P2_Tower_Red;
                        if (color == "START") return P2_Tower_Start;
                        if (color == "STOP") return P2_Tower_Stop;
                        break;
                    case 3:
                        if (color == "GREEN") return P3_Tower_Green;
                        if (color == "YELLOW") return P3_Tower_Yellow;
                        if (color == "RED") return P3_Tower_Red;
                        if (color == "START") return P3_Tower_Start;
                        if (color == "STOP") return P3_Tower_Stop;
                        break;
                    case 4:
                        if (color == "GREEN") return P4_Tower_Green;
                        if (color == "YELLOW") return P4_Tower_Yellow;
                        if (color == "RED") return P4_Tower_Red;
                        if (color == "START") return P4_Tower_Start;
                        if (color == "STOP") return P4_Tower_Stop;
                        break;
                }

                throw new ArgumentException($"Invalid port ({port}) or color ({color})");
            }
            #endregion

        }

        /// <summary>
        /// Địa chỉ Data (dữ liệu)
        /// </summary>
        public static class Data
        {

            // Port1
            public const string P1_X_Pos_Cur =  "TM332";
            public const string P1_RI_Pos_Cur = "TM334";
            public const string P1_Y_Pos_Cur =  "TM336";
            public const string P1_RO_Pos_Cur = "TM338";
            public const string P1_Z_Pos_Cur =  "TM340";
            public const string P1_F_Pos_Cur =  "TM344";
            public const string P1_X_ABS_Setpoint =     "DM370";
            public const string P1_Y_ABS_Setpoint =     "DM400";
            public const string P1_RI_ABS_Setpoint =    "DM460";
            public const string P1_RI_INC_Setpoint =    "DM464";
            public const string P1_X_Master = "DM2082";
            public const string P1_Y_Master = "DM2084";
            public const string P1_R_Master = "DM2086";
            // Port2
            public const string P2_X_Pos_Cur =  "TM300";
            public const string P2_RI_Pos_Cur = "TM302";
            public const string P2_Y_Pos_Cur =  "TM304";
            public const string P2_RO_Pos_Cur = "TM306";
            public const string P2_Z_Pos_Cur =  "TM308";
            public const string P2_F_Pos_Cur =  "TM312";
            public const string P2_X_ABS_Setpoint =     "DM10";
            public const string P2_Y_ABS_Setpoint =     "DM40";
            public const string P2_RI_ABS_Setpoint =    "DM100";
            public const string P2_RI_INC_Setpoint =    "DM104";
            public const string P2_X_Master = "DM1282";
            public const string P2_Y_Master = "DM1284";
            public const string P2_R_Master = "DM1286";
            // Port3
            public const string P3_X_Pos_Cur =  "TM348";
            public const string P3_RI_Pos_Cur = "TM350";
            public const string P3_Y_Pos_Cur =  "TM352";
            public const string P3_RO_Pos_Cur = "TM354";
            public const string P3_Z_Pos_Cur =  "TM356";
            public const string P3_F_Pos_Cur =  "TM360";
            public const string P3_X_ABS_Setpoint =     "DM550";
            public const string P3_Y_ABS_Setpoint =     "DM580";
            public const string P3_RI_ABS_Setpoint =    "DM640";
            public const string P3_RI_INC_Setpoint =    "DM644";
            public const string P3_X_Master = "DM2482";
            public const string P3_Y_Master = "DM2484";
            public const string P3_R_Master = "DM2486";
            // Port4
            public const string P4_X_Pos_Cur =  "TM316";
            public const string P4_RI_Pos_Cur = "TM318";
            public const string P4_Y_Pos_Cur =  "TM320";
            public const string P4_RO_Pos_Cur = "TM322";
            public const string P4_Z_Pos_Cur =  "TM324";
            public const string P4_F_Pos_Cur =  "TM328";
            public const string P4_X_ABS_Setpoint =     "DM190";
            public const string P4_Y_ABS_Setpoint =     "DM220";
            public const string P4_RI_ABS_Setpoint =    "DM280";
            public const string P4_RI_INC_Setpoint =    "DM284";
            public const string P4_X_Master = "DM1682";
            public const string P4_Y_Master = "DM1684";
            public const string P4_R_Master = "DM1686";

        }

    }
}
